# Generated by Django 2.0.7 on 2019-07-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20190725_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='tDemand',
            field=models.CharField(default='tDemand', max_length=200),
        ),
        migrations.AlterField(
            model_name='stock',
            name='tDescription',
            field=models.CharField(blank=True, default='tDescription', max_length=200),
        ),
        migrations.AlterField(
            model_name='stock',
            name='tDirector',
            field=models.CharField(default='tDirector', max_length=200),
        ),
        migrations.AlterField(
            model_name='stock',
            name='tForecast',
            field=models.CharField(default='tForecast', max_length=200),
        ),
    ]
