# Generated by Django 2.0.7 on 2019-07-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20190725_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='weekTendency',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='weekTendencyA',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='weekTendencyB',
            field=models.FloatField(default=0.0),
        ),
    ]
