# Generated by Django 2.0.7 on 2019-07-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20190725_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quantityHistory',
            field=models.TextField(default='{}'),
        ),
    ]
