# Generated by Django 2.0.5 on 2019-07-27 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_stock_quantityhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tCurrentPrice', models.FloatField(default=0.0)),
                ('tMarketCap', models.BigIntegerField(default=0)),
                ('tTotalShares', models.BigIntegerField(default=0)),
                ('tAvailableShares', models.BigIntegerField(default=0)),
                ('tForecast', models.CharField(default='tForecast', max_length=20)),
                ('tDemand', models.CharField(default='tDemand', max_length=20)),
                ('timestamp', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='timestamp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='history',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stock'),
        ),
    ]
