# Generated by Django 2.0.5 on 2019-07-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20190727_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='tDemand',
            field=models.CharField(default='Average', max_length=20),
        ),
        migrations.AlterField(
            model_name='history',
            name='tForecast',
            field=models.CharField(default='Average', max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='tDemand',
            field=models.CharField(default='Average', max_length=200),
        ),
        migrations.AlterField(
            model_name='stock',
            name='tForecast',
            field=models.CharField(default='Average', max_length=200),
        ),
    ]
