# Generated by Django 2.2.7 on 2019-12-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_auto_20191220_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='averagePrice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='triggers',
            field=models.TextField(default='{}'),
        ),
    ]
