# Generated by Django 3.1.7 on 2021-04-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_auto_20191220_2325'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['stock_id', 'timestamp'], name='stock_histo_stock_i_937d56_idx'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['timestamp'], name='stock_histo_timesta_bd1231_idx'),
        ),
    ]
