# Generated by Django 3.1.2 on 2020-11-30 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0002_npc_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(default=0)),
                ('vote', models.IntegerField(default=0)),
                ('users', models.TextField(default='{}')),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loot.npc')),
            ],
        ),
    ]
