# Generated by Django 3.1.2 on 2020-11-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0003_scheduledattack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledattack',
            old_name='date',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='scheduledattack',
            name='author',
            field=models.CharField(default='Player [1]', max_length=32),
        ),
    ]
