# Generated by Django 3.0.1 on 2020-01-23 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='membersUpda',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tId', models.IntegerField(default=0, unique=True)),
                ('name', models.CharField(default='Duke', max_length=15)),
                ('daysInFaction', models.IntegerField(default=0)),
                ('lastAction', models.CharField(default='-', max_length=200)),
                ('lastActionTS', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=128)),
                ('details', models.CharField(blank=True, default='', max_length=128)),
                ('state', models.CharField(blank=True, default='', max_length=32)),
                ('color', models.CharField(blank=True, default='', max_length=16)),
                ('until', models.IntegerField(default=0)),
                ('shareE', models.IntegerField(default=-1)),
                ('energy', models.IntegerField(default=0)),
                ('shareN', models.IntegerField(default=-1)),
                ('nnb', models.IntegerField(default=0)),
                ('arson', models.IntegerField(default=0)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faction.Faction')),
            ],
        ),
    ]
