# Generated by Django 3.0.1 on 2020-01-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0002_auto_20200123_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='hitsThreshold',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='faction',
            name='poster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faction',
            name='posterHold',
            field=models.BooleanField(default=False),
        ),
    ]
