# Generated by Django 3.0.1 on 2020-01-27 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0006_faction_memberstatusupda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tId', models.IntegerField(default=0)),
                ('chain', models.IntegerField(default=0)),
                ('start', models.IntegerField(default=0)),
                ('end', models.IntegerField(default=0)),
                ('respect', models.FloatField(default=0)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faction.Faction')),
            ],
        ),
    ]
