# Generated by Django 3.0.1 on 2020-01-27 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0008_auto_20200127_2223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttackChain',
        ),
    ]
