# Generated by Django 3.0.1 on 2020-01-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0010_attackchain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chain',
            old_name='lastUpdate',
            new_name='update',
        ),
        migrations.AddField(
            model_name='chain',
            name='last',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chain',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
