# Generated by Django 3.0.1 on 2020-01-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0011_auto_20200128_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='crontab',
            field=models.IntegerField(default=0),
        ),
    ]
