# Generated by Django 3.0.1 on 2020-01-28 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0012_chain_crontab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attackerId', models.IntegerField(default=0)),
                ('name', models.CharField(default='Duke', max_length=15)),
                ('hits', models.IntegerField(default=0)),
                ('bonus', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('respect', models.FloatField(default=0)),
                ('fairFight', models.FloatField(default=0)),
                ('war', models.FloatField(default=0)),
                ('retaliation', models.FloatField(default=0)),
                ('groupAttack', models.FloatField(default=0)),
                ('overseas', models.FloatField(default=0)),
                ('daysInFaction', models.IntegerField(default=0)),
                ('beenThere', models.BooleanField(default=False)),
                ('graph', models.TextField(blank=True, default='', null=True)),
                ('watcher', models.FloatField(default=0)),
                ('warhits', models.IntegerField(default=0)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faction.Chain')),
            ],
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tId', models.IntegerField(default=0)),
                ('name', models.CharField(default='Duke', max_length=15)),
                ('hit', models.IntegerField(default=0)),
                ('respect', models.FloatField(default=0)),
                ('targetId', models.IntegerField(default=0)),
                ('targetName', models.CharField(default='Unkown', max_length=15)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faction.Chain')),
            ],
        ),
    ]
