# Generated by Django 3.0.1 on 2020-01-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0013_bonus_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='lastAttacksPulled',
            field=models.IntegerField(default=0),
        ),
    ]
