# Generated by Django 3.0.1 on 2020-01-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0014_faction_lastattackspulled'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='attacks',
            field=models.IntegerField(default=0),
        ),
    ]
