# Generated by Django 3.0.1 on 2020-01-30 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0016_wall'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttacksReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(default=0)),
                ('end', models.IntegerField(default=0)),
                ('last', models.IntegerField(default=0)),
                ('live', models.BooleanField(default=False)),
                ('computing', models.BooleanField(default=True)),
                ('attackerFactions', models.TextField(default='[]')),
                ('defenderFactions', models.TextField(default='[]')),
                ('defends', models.IntegerField(default=0)),
                ('attacks', models.IntegerField(default=0)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faction.Faction')),
            ],
        ),
        migrations.CreateModel(
            name='AttackReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tId', models.IntegerField(default=0)),
                ('timestamp_started', models.IntegerField(default=0)),
                ('timestamp_ended', models.IntegerField(default=0)),
                ('attacker_id', models.IntegerField(default=0)),
                ('attacker_name', models.CharField(blank=True, default='attacker_name', max_length=16, null=True)),
                ('attacker_faction', models.IntegerField(default=0)),
                ('attacker_factionname', models.CharField(blank=True, default='attacker_factionname', max_length=32, null=True)),
                ('defender_id', models.IntegerField(default=0)),
                ('defender_name', models.CharField(blank=True, default='defender_name', max_length=16, null=True)),
                ('defender_faction', models.IntegerField(default=0)),
                ('defender_factionname', models.CharField(blank=True, default='defender_factionname', max_length=32, null=True)),
                ('result', models.CharField(default='result', max_length=32)),
                ('stealthed', models.IntegerField(default=0)),
                ('respect_gain', models.FloatField(default=0.0)),
                ('chain', models.IntegerField(default=0)),
                ('fairFight', models.FloatField(default=0.0)),
                ('war', models.IntegerField(default=0)),
                ('retaliation', models.FloatField(default=0.0)),
                ('groupAttack', models.FloatField(default=0.0)),
                ('overseas', models.FloatField(default=0.0)),
                ('chainBonus', models.IntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faction.AttacksReport')),
            ],
        ),
    ]
