# Generated by Django 3.0.1 on 2020-01-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0017_attackreport_attacksreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacksreport',
            name='crontab',
            field=models.IntegerField(default=0),
        ),
    ]
