# Generated by Django 3.0.1 on 2020-01-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0018_attacksreport_crontab'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacksreport',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
