# Generated by Django 3.0.1 on 2020-01-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0019_attacksreport_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacksreport',
            name='update',
            field=models.IntegerField(default=0),
        ),
    ]
