# Generated by Django 3.0.1 on 2020-01-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0020_attacksreport_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacksreport',
            name='wall',
            field=models.ManyToManyField(blank=True, to='faction.Wall'),
        ),
    ]
