# Generated by Django 3.0.1 on 2020-02-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0024_faction_armoryupda'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='armoryOld',
            field=models.IntegerField(default=8035200),
        ),
    ]
