# Generated by Django 3.0.1 on 2020-02-02 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0025_faction_armoryold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=0)),
                ('timestampday', models.IntegerField(default=0)),
                ('money', models.IntegerField(default=0)),
                ('donations', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('respect', models.IntegerField(default=0)),
                ('medicalitemsused', models.IntegerField(default=0)),
                ('criminaloffences', models.IntegerField(default=0)),
                ('organisedcrimerespect', models.IntegerField(default=0)),
                ('organisedcrimemoney', models.IntegerField(default=0)),
                ('organisedcrimesuccess', models.IntegerField(default=0)),
                ('organisedcrimefail', models.IntegerField(default=0)),
                ('attackswon', models.IntegerField(default=0)),
                ('attackslost', models.IntegerField(default=0)),
                ('attacksleave', models.IntegerField(default=0)),
                ('attacksmug', models.IntegerField(default=0)),
                ('attackshosp', models.IntegerField(default=0)),
                ('bestchain', models.IntegerField(default=0)),
                ('busts', models.IntegerField(default=0)),
                ('revives', models.IntegerField(default=0)),
                ('jails', models.IntegerField(default=0)),
                ('hosps', models.IntegerField(default=0)),
                ('medicalitemrecovery', models.IntegerField(default=0)),
                ('medicalcooldownused', models.IntegerField(default=0)),
                ('gymtrains', models.IntegerField(default=0)),
                ('gymstrength', models.IntegerField(default=0)),
                ('gymspeed', models.IntegerField(default=0)),
                ('gymdefense', models.IntegerField(default=0)),
                ('gymdexterity', models.IntegerField(default=0)),
                ('candyused', models.IntegerField(default=0)),
                ('alcoholused', models.IntegerField(default=0)),
                ('energydrinkused', models.IntegerField(default=0)),
                ('drugsused', models.IntegerField(default=0)),
                ('drugoverdoses', models.IntegerField(default=0)),
                ('rehabs', models.IntegerField(default=0)),
                ('caymaninterest', models.IntegerField(default=0)),
                ('traveltimes', models.IntegerField(default=0)),
                ('traveltime', models.IntegerField(default=0)),
                ('hunting', models.IntegerField(default=0)),
                ('attacksdamagehits', models.IntegerField(default=0)),
                ('attacksdamage', models.IntegerField(default=0)),
                ('hosptimegiven', models.IntegerField(default=0)),
                ('hosptimereceived', models.IntegerField(default=0)),
                ('attacksdamaging', models.IntegerField(default=0)),
                ('attacksrunaway', models.IntegerField(default=0)),
                ('highestterritories', models.IntegerField(default=0)),
                ('territoryrespect', models.IntegerField(default=0)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faction.Faction')),
            ],
        ),
    ]
