# Generated by Django 3.0.1 on 2020-02-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0026_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='donations',
            new_name='donationsmoney',
        ),
        migrations.AddField(
            model_name='log',
            name='donationspoints',
            field=models.IntegerField(default=0),
        ),
    ]
