# Generated by Django 3.0.1 on 2020-02-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0027_auto_20200202_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news',
            field=models.CharField(default='news', max_length=256),
        ),
    ]
