# Generated by Django 3.0.1 on 2020-02-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0029_auto_20200202_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='donationsmoney',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='log',
            name='money',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='log',
            name='respect',
            field=models.BigIntegerField(default=0),
        ),
    ]
