# Generated by Django 3.0.1 on 2020-02-03 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0033_factiondata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factiondata',
            old_name='contrabs',
            new_name='crontabs',
        ),
    ]
