# Generated by Django 2.0.7 on 2020-02-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0036_racket_territory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactionTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tId', models.IntegerField(default=0)),
                ('lvl', models.IntegerField(default=0)),
                ('branch', models.CharField(default='branch', max_length=32)),
                ('name', models.CharField(default='name', max_length=32)),
                ('ability', models.CharField(default='ability', max_length=256)),
                ('challenge', models.CharField(default='challenge', max_length=256)),
                ('base_cost', models.IntegerField(default=0)),
            ],
        ),
    ]
