# Generated by Django 2.0.7 on 2020-02-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0039_upgrade_simu'),
    ]

    operations = [
        migrations.AddField(
            model_name='factiontree',
            name='maxlevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='factiontree',
            name='shortname',
            field=models.CharField(default='name', max_length=32),
        ),
    ]
