# Generated by Django 2.0.7 on 2020-02-07 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0040_auto_20200204_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tId', models.IntegerField(default=0)),
                ('timestamp', models.IntegerField(default=0)),
                ('reviver_id', models.IntegerField(default=0)),
                ('reviver_name', models.CharField(default='reviver_name', max_length=32)),
                ('reviver_faction', models.IntegerField(default=0)),
                ('reviver_factionname', models.CharField(blank=True, default='reviver_factionname', max_length=64, null=True)),
                ('target_id', models.IntegerField(default=0)),
                ('target_name', models.CharField(default='target_name', max_length=32)),
                ('target_faction', models.IntegerField(default=0)),
                ('target_factionname', models.CharField(blank=True, default='target_factionname', max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RevivesReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(default=0)),
                ('end', models.IntegerField(default=0)),
                ('last', models.IntegerField(default=0)),
                ('live', models.BooleanField(default=True)),
                ('computing', models.BooleanField(default=True)),
                ('state', models.IntegerField(default=0)),
                ('crontab', models.IntegerField(default=0)),
                ('update', models.IntegerField(default=0)),
                ('reviverFactions', models.TextField(default='[]')),
                ('targetFactions', models.TextField(default='[]')),
                ('revivesMade', models.IntegerField(default=0)),
                ('targetsReceived', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='faction',
            name='lastRevivesPulled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revivesreport',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faction.Faction'),
        ),
        migrations.AddField(
            model_name='revive',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faction.RevivesReport'),
        ),
    ]
