# Generated by Django 3.0.1 on 2020-02-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0042_auto_20200207_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
