# Generated by Django 3.0.1 on 2020-02-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0043_upgrade_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='shortname',
            field=models.CharField(default='name', max_length=32),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='unlocked',
            field=models.CharField(blank=True, default='branch', max_length=32, null=True),
        ),
    ]
