# Generated by Django 3.0.1 on 2020-02-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0044_auto_20200209_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='branch',
            field=models.CharField(default='name', max_length=32),
        ),
    ]
