# Generated by Django 2.0.7 on 2020-02-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0045_upgrade_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='unsets_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='unlocked',
            field=models.CharField(blank=True, default='unlocked', max_length=32, null=True),
        ),
    ]
