# Generated by Django 3.0.1 on 2020-02-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0047_auto_20200210_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='upgradesUpda',
            field=models.IntegerField(default=0),
        ),
    ]
