# Generated by Django 2.0.7 on 2020-02-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0048_faction_upgradesupda'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='discordName',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
