# Generated by Django 2.0.7 on 2020-02-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0049_faction_discordname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faction',
            name='armoryOld',
        ),
        migrations.AddField(
            model_name='faction',
            name='armoryHist',
            field=models.CharField(default='three_months', max_length=16),
        ),
        migrations.AddField(
            model_name='faction',
            name='attacksHist',
            field=models.CharField(default='three_months', max_length=16),
        ),
        migrations.AddField(
            model_name='faction',
            name='chainsHist',
            field=models.CharField(default='one_year', max_length=16),
        ),
        migrations.AddField(
            model_name='faction',
            name='revivesHist',
            field=models.CharField(default='three_months', max_length=16),
        ),
    ]
