# Generated by Django 2.0.7 on 2020-02-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0050_auto_20200213_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='liveLength',
            field=models.CharField(default='one_week', max_length=16),
        ),
    ]
