# Generated by Django 2.0.7 on 2020-02-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0051_faction_livelength'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='cooldown',
            field=models.BooleanField(default=False),
        ),
    ]
