# Generated by Django 3.0.1 on 2020-02-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0052_chain_cooldown'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='addToEnd',
            field=models.IntegerField(default=0),
        ),
    ]
