# Generated by Django 3.0.1 on 2020-02-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0053_chain_addtoend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='addToEnd',
            field=models.IntegerField(default=10),
        ),
    ]
