# Generated by Django 3.0.1 on 2020-02-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0055_attacksfaction_attacksplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacksplayer',
            name='player_faction_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attacksplayer',
            name='player_faction_name',
            field=models.CharField(blank=True, default='faction_name', max_length=64, null=True),
        ),
    ]
