# Generated by Django 3.0.1 on 2020-02-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0056_auto_20200227_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attacksfaction',
            old_name='type',
            new_name='attacked',
        ),
        migrations.RenameField(
            model_name='attacksfaction',
            old_name='wins',
            new_name='defends',
        ),
        migrations.AddField(
            model_name='attacksfaction',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
