# Generated by Django 3.0.1 on 2020-02-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0058_auto_20200227_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attacksplayer',
            old_name='show',
            new_name='showA',
        ),
        migrations.AddField(
            model_name='attacksplayer',
            name='showD',
            field=models.BooleanField(default=False),
        ),
    ]
