# Generated by Django 3.0.1 on 2020-03-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0060_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, default='Short description', max_length=256, null=True),
        ),
    ]
