# Generated by Django 3.0.1 on 2020-03-07 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0062_auto_20200303_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevivesPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(default=0)),
                ('player_name', models.CharField(blank=True, default='player_name', max_length=16, null=True)),
                ('player_faction_id', models.IntegerField(default=0)),
                ('player_faction_name', models.CharField(blank=True, default='faction_name', max_length=64, null=True)),
                ('revivesMade', models.IntegerField(default=0)),
                ('revivesReceived', models.IntegerField(default=0)),
                ('showA', models.BooleanField(default=False)),
                ('showD', models.BooleanField(default=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faction.RevivesReport')),
            ],
        ),
        migrations.CreateModel(
            name='RevivesFaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faction_id', models.IntegerField(default=0)),
                ('faction_name', models.CharField(blank=True, default='faction_name', max_length=64, null=True)),
                ('revivesMade', models.IntegerField(default=0)),
                ('revivesReceived', models.IntegerField(default=0)),
                ('showA', models.BooleanField(default=False)),
                ('showD', models.BooleanField(default=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faction.RevivesReport')),
            ],
        ),
    ]
