# Generated by Django 3.0.1 on 2020-03-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0063_revivesfaction_revivesplayer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revivesfaction',
            old_name='showA',
            new_name='show',
        ),
        migrations.RenameField(
            model_name='revivesreport',
            old_name='reviverFactions',
            new_name='factions',
        ),
        migrations.RemoveField(
            model_name='revivesfaction',
            name='showD',
        ),
        migrations.RemoveField(
            model_name='revivesreport',
            name='targetFactions',
        ),
    ]
