# Generated by Django 3.0.1 on 2020-03-08 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0064_auto_20200308_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revivesplayer',
            old_name='showA',
            new_name='show',
        ),
        migrations.RemoveField(
            model_name='revivesplayer',
            name='showD',
        ),
    ]
