# Generated by Django 3.0.1 on 2020-03-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0065_auto_20200308_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='lastActionStatus',
            field=models.CharField(default='Offline', max_length=16),
        ),
    ]
