# Generated by Django 3.0.1 on 2020-03-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0067_event_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='revive',
            name='target_hospital_reason',
            field=models.CharField(default='Unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='revive',
            name='target_online_status',
            field=models.CharField(default='Unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='revivesfaction',
            name='revivesMadeH',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revivesfaction',
            name='revivesMadeO',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revivesfaction',
            name='revivesReceivedH',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revivesfaction',
            name='revivesReceivedO',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revivesplayer',
            name='revivesMadeH',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revivesplayer',
            name='revivesMadeO',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revivesplayer',
            name='revivesReceivedH',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revivesplayer',
            name='revivesReceivedO',
            field=models.IntegerField(default=0),
        ),
    ]
