# Generated by Django 3.0.1 on 2020-03-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0068_auto_20200310_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='revivesfaction',
            name='revivesMadeB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revivesfaction',
            name='revivesReceivedB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revivesplayer',
            name='revivesMadeB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revivesplayer',
            name='revivesReceivedB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revivesreport',
            name='filter',
            field=models.IntegerField(default=0),
        ),
    ]
