# Generated by Django 3.0.1 on 2020-03-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0069_auto_20200310_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revive',
            name='target_online_status',
        ),
        migrations.AddField(
            model_name='revive',
            name='target_last_action_status',
            field=models.CharField(blank=True, default='Unkown', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='revive',
            name='target_last_action_timestamp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='revive',
            name='target_hospital_reason',
            field=models.CharField(blank=True, default='Unkown', max_length=32, null=True),
        ),
    ]
