# Generated by Django 3.0.1 on 2020-03-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0070_auto_20200310_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revive',
            name='target_hospital_reason',
            field=models.CharField(blank=True, default='Unkown', max_length=128, null=True),
        ),
    ]
