# Generated by Django 3.0.1 on 2020-03-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0073_chain_shareid'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacksreport',
            name='shareId',
            field=models.SlugField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='revivesreport',
            name='shareId',
            field=models.SlugField(blank=True, default='', max_length=32, null=True),
        ),
    ]
