# Generated by Django 3.0.1 on 2020-03-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0074_auto_20200323_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='racket',
            name='assaulting_faction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='racket',
            name='defending_faction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='racket',
            name='ends',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='racket',
            name='started',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='racket',
            name='war',
            field=models.BooleanField(default=False),
        ),
    ]
