# Generated by Django 3.0.1 on 2020-03-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0075_auto_20200324_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='member',
            field=models.CharField(default='?', max_length=32),
        ),
    ]
