# Generated by Django 3.0.1 on 2020-03-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0076_news_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='armoryNewsFilter',
            field=models.CharField(default='', max_length=32),
        ),
    ]
