# Generated by Django 3.0.1 on 2020-03-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0077_faction_armorynewsfilter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attacksreport',
            old_name='attackerFactions',
            new_name='factions',
        ),
        migrations.RemoveField(
            model_name='attacksreport',
            name='defenderFactions',
        ),
        migrations.AddField(
            model_name='attacksreport',
            name='filter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attacksreport',
            name='player_filter',
            field=models.IntegerField(default=0),
        ),
    ]
