# Generated by Django 3.0.1 on 2020-03-26 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0078_auto_20200326_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attacksfaction',
            old_name='showA',
            new_name='show',
        ),
        migrations.RenameField(
            model_name='attacksplayer',
            old_name='showA',
            new_name='show',
        ),
        migrations.RemoveField(
            model_name='attacksfaction',
            name='showD',
        ),
        migrations.RemoveField(
            model_name='attacksplayer',
            name='showD',
        ),
    ]
