# Generated by Django 3.0.1 on 2020-03-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0079_auto_20200326_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacksreport',
            name='fill',
            field=models.IntegerField(default=0),
        ),
    ]
