# Generated by Django 3.0.4 on 2020-04-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0081_chain_respectcomputed'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='defense',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='dexterity',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='shareS',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='member',
            name='speed',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='strength',
            field=models.BigIntegerField(default=0),
        ),
    ]
