# Generated by Django 3.0.4 on 2020-04-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0082_auto_20200403_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attackchain',
            name='chainBonus',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='attackreport',
            name='chainBonus',
            field=models.FloatField(default=0.0),
        ),
    ]
