# Generated by Django 3.0.4 on 2020-05-08 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0083_auto_20200415_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tId', models.IntegerField(default=0)),
                ('crime_id', models.IntegerField(default=0)),
                ('crime_name', models.CharField(default='Crime Name', max_length=64)),
                ('time_started', models.IntegerField(default=0)),
                ('time_ready', models.IntegerField(default=0)),
                ('time_completed', models.IntegerField(default=0)),
                ('initiated_by', models.IntegerField(default=0)),
                ('planned_by', models.IntegerField(default=0)),
                ('money_gain', models.IntegerField(default=0)),
                ('respect_gain', models.IntegerField(default=0)),
                ('time_left', models.BooleanField(default=0)),
                ('initiated', models.BooleanField(default=0)),
                ('success', models.BooleanField(default=0)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faction.Faction')),
            ],
        ),
    ]
