# Generated by Django 3.0.4 on 2020-05-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0084_crimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='crimesHist',
            field=models.CharField(default='one_months', max_length=16),
        ),
        migrations.AddField(
            model_name='faction',
            name='crimesUpda',
            field=models.IntegerField(default=0),
        ),
    ]
