# Generated by Django 3.0.4 on 2020-05-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0085_auto_20200508_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimes',
            name='time_left',
            field=models.IntegerField(default=0),
        ),
    ]
