# Generated by Django 3.0.4 on 2020-05-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0086_auto_20200508_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='crimesHist',
            field=models.CharField(default='one_month', max_length=16),
        ),
    ]
