# Generated by Django 3.0.4 on 2020-05-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0087_auto_20200508_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimes',
            name='participants',
            field=models.CharField(default=[], max_length=256),
        ),
        migrations.AddField(
            model_name='crimes',
            name='ready',
            field=models.BooleanField(default=0),
        ),
    ]
