# Generated by Django 3.0.4 on 2020-05-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0088_auto_20200508_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimes',
            name='team_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crimes',
            name='participants',
            field=models.CharField(default='[]', max_length=256),
        ),
    ]
