# Generated by Django 3.0.8 on 2020-07-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0089_auto_20200509_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='shareE',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='shareN',
            field=models.IntegerField(default=1),
        ),
    ]
