# Generated by Django 3.0.8 on 2020-08-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0090_auto_20200729_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='crimesDump',
            field=models.TextField(default='{}'),
        ),
    ]
