# Generated by Django 3.0.8 on 2020-08-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0091_faction_crimesdump'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='crimesRank',
            field=models.TextField(default='{}'),
        ),
    ]
