# Generated by Django 3.0.8 on 2020-08-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0092_faction_crimesrank'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='pj_pa_Dump',
            field=models.TextField(default='{}'),
        ),
    ]
