# Generated by Django 3.1.1 on 2020-10-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0095_member_crimesrank'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='simulationID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faction',
            name='simulationTS',
            field=models.IntegerField(default=0),
        ),
    ]
