# Generated by Django 3.1.2 on 2020-10-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0096_auto_20201002_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='armoryNewsFilter',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
