# Generated by Django 3.1.2 on 2020-10-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0096_auto_20201002_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='posterImg',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
