# Generated by Django 3.1.2 on 2020-10-21 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0097_faction_posterimg'),
        ('faction', '0097_auto_20201021_2158'),
    ]

    operations = [
    ]
