# Generated by Django 3.1.2 on 2020-12-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0099_member_singlehithonors'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='energyRefillUsed',
            field=models.BooleanField(default=False),
        ),
    ]
