# Generated by Django 3.1.2 on 2020-12-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0100_member_energyrefillused'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='drugCD',
            field=models.IntegerField(default=0),
        ),
    ]
