# Generated by Django 3.1.2 on 2020-12-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0102_remove_faction_crimesdump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='crimesRank',
            field=models.IntegerField(default=100),
        ),
    ]
