# Generated by Django 3.1.5 on 2021-01-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0104_member_bonusscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='posterGymImg',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
