# Generated by Django 3.1.5 on 2021-01-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0105_faction_postergymimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='posterHeadImg',
            field=models.ImageField(blank=True, upload_to='posters'),
        ),
        migrations.AddField(
            model_name='faction',
            name='posterTailImg',
            field=models.ImageField(blank=True, upload_to='posters'),
        ),
    ]
