# Generated by Django 3.1.5 on 2021-01-24 15:31

from django.db import migrations, models
import faction.models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0106_auto_20210124_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='posterHeadImg',
            field=models.ImageField(blank=True, upload_to=faction.models.posterRenameHead),
        ),
        migrations.AlterField(
            model_name='faction',
            name='posterTailImg',
            field=models.ImageField(blank=True, upload_to=faction.models.posterRenameTail),
        ),
    ]
