# Generated by Django 3.1.5 on 2021-01-24 15:37

from django.db import migrations, models
import faction.models
import faction.storage


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0107_auto_20210124_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='posterHeadImg',
            field=models.ImageField(blank=True, max_length=64, storage=faction.storage.OverwriteStorage(), upload_to=faction.models.posterRenameHead),
        ),
        migrations.AlterField(
            model_name='faction',
            name='posterTailImg',
            field=models.ImageField(blank=True, max_length=64, storage=faction.storage.OverwriteStorage(), upload_to=faction.models.posterRenameTail),
        ),
    ]
