# Generated by Django 3.1.5 on 2021-01-30 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0108_auto_20210124_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attacksreport',
            name='fill',
        ),
    ]
