# Generated by Django 3.1.5 on 2021-02-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0109_remove_attacksreport_fill'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='revive',
            field=models.BooleanField(default=False),
        ),
    ]
