# Generated by Django 3.1.5 on 2021-02-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0110_member_revive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tId',
            field=models.CharField(default='a', max_length=32),
        ),
    ]
