# Generated by Django 3.1.5 on 2021-02-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0112_auto_20210223_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='revivesreport',
            name='include_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revivesreport',
            name='success_rate',
            field=models.IntegerField(default=0),
        ),
    ]
