# Generated by Django 3.1.5 on 2021-02-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0113_auto_20210223_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revivesreport',
            old_name='success_rate',
            new_name='revivesMadeSuccess',
        ),
        migrations.AddField(
            model_name='revivesreport',
            name='revivesReceivedSuccess',
            field=models.IntegerField(default=0),
        ),
    ]
