# Generated by Django 3.1.5 on 2021-03-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0116_auto_20210323_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='attackreport',
            name='raid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attackreport',
            name='respect',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='attackreport',
            name='respect_lost',
            field=models.FloatField(default=0.0),
        ),
    ]
