# Generated by Django 3.1.5 on 2021-03-31 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0117_auto_20210323_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmoryReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(default=0)),
                ('end', models.IntegerField(default=0)),
                ('last', models.IntegerField(default=0)),
                ('live', models.BooleanField(default=True)),
                ('computing', models.BooleanField(default=True)),
                ('state', models.IntegerField(default=0)),
                ('crontab', models.IntegerField(default=0)),
                ('update', models.IntegerField(default=0)),
                ('report', models.TextField(default='{}')),
                ('news_ids', models.TextField(default='[]')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faction.faction')),
            ],
        ),
    ]
