# Generated by Django 3.1.5 on 2021-04-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0118_armoryreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='armoryreport',
            name='n_news',
            field=models.IntegerField(default=0),
        ),
    ]
