# Generated by Django 3.1.5 on 2021-04-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0119_armoryreport_n_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='armoryreport',
            name='state_string',
            field=models.CharField(default='No reports', max_length=32),
        ),
        migrations.AddField(
            model_name='revivesreport',
            name='chance_filter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='revivesreport',
            name='include_failed',
            field=models.BooleanField(default=True),
        ),
    ]
