# Generated by Django 3.1.5 on 2021-04-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0120_auto_20210404_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='revivesfaction',
            name='revivesMadeBSuccess',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revivesfaction',
            name='revivesMadeHSuccess',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revivesfaction',
            name='revivesMadeOSuccess',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revivesfaction',
            name='revivesMadeSuccess',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revivesfaction',
            name='revivesReceivedBSuccess',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revivesfaction',
            name='revivesReceivedHSuccess',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revivesfaction',
            name='revivesReceivedOSuccess',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revivesfaction',
            name='revivesReceivedSuccess',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revivesplayer',
            name='revivesMadeBSuccess',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revivesplayer',
            name='revivesMadeHSuccess',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revivesplayer',
            name='revivesMadeOSuccess',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revivesplayer',
            name='revivesMadeSuccess',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revivesplayer',
            name='revivesReceivedBSuccess',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revivesplayer',
            name='revivesReceivedHSuccess',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revivesplayer',
            name='revivesReceivedOSuccess',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revivesplayer',
            name='revivesReceivedSuccess',
            field=models.IntegerField(default=0),
        ),
    ]
