# Generated by Django 3.1.5 on 2021-04-05 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0122_auto_20210405_2116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='news',
        ),
    ]
