# Generated by Django 3.1.5 on 2021-04-07 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0124_auto_20210407_1910'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spy',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='factions_spies',
        ),
    ]
