# Generated by Django 3.1.5 on 2021-04-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0126_spy_spydatabase'),
    ]

    operations = [
        migrations.AddField(
            model_name='spydatabase',
            name='name',
            field=models.CharField(default='My spy database', max_length=64),
        ),
    ]
