# Generated by Django 3.1.5 on 2021-04-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0127_spydatabase_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='spydatabase',
            name='master_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spydatabase',
            name='secret',
            field=models.CharField(default='x', max_length=16),
        ),
    ]
