# Generated by Django 3.1.5 on 2021-04-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0128_auto_20210407_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='spydatabase',
            name='n_spies',
            field=models.IntegerField(default=0),
        ),
    ]
