# Generated by Django 3.1.5 on 2021-04-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0129_spydatabase_n_spies'),
    ]

    operations = [
        migrations.AddField(
            model_name='spy',
            name='update',
            field=models.IntegerField(default=0),
        ),
    ]
