# Generated by Django 3.1.5 on 2021-04-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0131_spydatabase_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='spydatabase',
            name='use_api',
            field=models.BooleanField(default=False),
        ),
    ]
