# Generated by Django 3.1.5 on 2021-04-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0132_spydatabase_use_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimes',
            name='participants',
            field=models.CharField(default='[]', max_length=512),
        ),
    ]
