# Generated by Django 3.1.5 on 2021-05-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0134_auto_20210511_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='targetName',
            field=models.CharField(default='Unknown', max_length=15),
        ),
        migrations.AlterField(
            model_name='revive',
            name='target_hospital_reason',
            field=models.CharField(blank=True, default='Unknown', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='revive',
            name='target_last_action_status',
            field=models.CharField(blank=True, default='Unknown', max_length=16, null=True),
        ),
    ]
