# Generated by Django 3.1.5 on 2021-05-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0135_auto_20210521_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='attacks_last_hour',
            field=models.IntegerField(default=0),
        ),
    ]
