# Generated by Django 3.1.5 on 2021-05-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0136_chain_attacks_last_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chain',
            name='attacks_last_hour',
        ),
    ]
