# Generated by Django 4.0.2 on 2022-02-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0139_auto_20211228_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='slots',
            field=models.IntegerField(default=0),
        ),
    ]
