# Generated by Django 4.0.2 on 2022-03-22 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0140_territory_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faction',
            name='memberStatus',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='memberStatusUpda',
        ),
    ]
