# Generated by Django 4.0.2 on 2022-06-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0143_attacksreport_war_id_attacksreport_war_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='posterPerksCurrent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='faction',
            name='posterPerksPeace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faction',
            name='posterPerksWar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faction',
            name='posterWar',
            field=models.BooleanField(default=False),
        ),
    ]
