# Generated by Django 4.0.2 on 2022-06-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0147_factiontarget_dibs_name_factiontarget_dibs_tid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='can_be_unset',
            field=models.IntegerField(default=0),
        ),
    ]
