# Generated by Django 4.0.2 on 2022-06-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0148_upgrade_can_be_unset'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='upgradeType',
            field=models.CharField(default='upgrades', max_length=16),
        ),
    ]
