# Generated by Django 4.0.5 on 2022-10-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0150_factiontarget_revivable'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='stats_ts',
            field=models.IntegerField(default=0),
        ),
    ]
