# Generated by Django 4.0.5 on 2023-01-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faction", "0151_member_stats_ts"),
    ]

    operations = [
        migrations.AddField(
            model_name="attackchain",
            name="warlord_bonus",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="attackreport",
            name="warlord_bonus",
            field=models.FloatField(default=0.0),
        ),
    ]
