# Generated by Django 4.0.5 on 2023-04-20 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faction", "0152_attackchain_warlord_bonus_attackreport_warlord_bonus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faction",
            name="ph_pa_Dump",
        ),
        migrations.RemoveField(
            model_name="member",
            name="arson",
        ),
    ]
