# Generated by Django 4.2.18 on 2025-09-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faction", "0153_remove_faction_ph_pa_dump_remove_member_arson"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="travel_type",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
