# Generated by Django 4.2.18 on 2025-09-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faction", "0154_member_travel_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="plane_image_type",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
