# Generated by Django 4.2.25 on 2026-02-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0155_member_plane_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='useOC2',
            field=models.BooleanField(default=False),
        ),
    ]
