# Generated by Django 4.2.25 on 2026-02-13 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0156_faction_useoc2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crimesv2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tID', models.IntegerField(default=0)),
                ('previous_crime_id', models.IntegerField(default=None)),
                ('name', models.CharField(default='Crime Name', max_length=64)),
                ('difficulty', models.IntegerField(default=0)),
                ('status', models.CharField(default='Status', max_length=32)),
                ('created_at', models.IntegerField(default=0)),
                ('executed_at', models.IntegerField(default=0)),
                ('ready_at', models.IntegerField(default=0)),
                ('expired_at', models.IntegerField(default=0)),
                ('slots', models.CharField(default='[]', max_length=512)),
                ('rewards', models.CharField(default='[]', max_length=512)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faction.faction')),
            ],
        ),
    ]
