# Generated by Django 4.2.25 on 2026-02-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0157_crimesv2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimesv2',
            name='previous_crime_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
