# Generated by Django 4.2.25 on 2026-02-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0158_alter_crimesv2_previous_crime_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimesv2',
            name='executed_at',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='crimesv2',
            name='expired_at',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='crimesv2',
            name='ready_at',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='crimesv2',
            name='rewards',
            field=models.CharField(blank=True, default='[]', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='crimesv2',
            name='slots',
            field=models.CharField(blank=True, default='[]', max_length=512, null=True),
        ),
    ]
