# Generated by Django 4.2.25 on 2026-02-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0159_alter_crimesv2_executed_at_alter_crimesv2_expired_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimesv2',
            name='rewards',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='crimesv2',
            name='slots',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
