# Generated by Django 4.2.25 on 2026-02-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0160_alter_crimesv2_rewards_alter_crimesv2_slots'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attackreport',
            index=models.Index(fields=['report', 'attacker_faction'], name='faction_att_report__2614b5_idx'),
        ),
        migrations.AddIndex(
            model_name='attackreport',
            index=models.Index(fields=['report', 'defender_faction'], name='faction_att_report__c771c4_idx'),
        ),
        migrations.AddIndex(
            model_name='attackreport',
            index=models.Index(fields=['report', 'timestamp_ended'], name='faction_att_report__8ca23f_idx'),
        ),
    ]
