# Generated by Django 2.0.5 on 2019-04-26 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tId', models.IntegerField(default=4, unique=True)),
                ('name', models.CharField(default='Duke', max_length=200)),
                ('apiKey', models.CharField(default='AAAA', max_length=16)),
                ('lastUpdateTS', models.IntegerField(default=django.utils.timezone.now)),
            ],
        ),
    ]
