# Generated by Django 2.0.5 on 2019-04-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='apiKey',
            new_name='key',
        ),
        migrations.AlterField(
            model_name='player',
            name='lastUpdateTS',
            field=models.IntegerField(default=0),
        ),
    ]
