# Generated by Django 2.0.5 on 2019-04-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20190426_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='factionInfo',
            field=models.TextField(default='{}'),
        ),
    ]
