# Generated by Django 2.0.5 on 2019-04-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_player_factioninfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='factionJson',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='player',
            name='factionInfo',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
