# Generated by Django 2.0.5 on 2019-04-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_auto_20190430_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='factionInfo',
            new_name='chainInfo',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='factionJson',
            new_name='chainJson',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='factionUpda',
            new_name='chainUpda',
        ),
        migrations.AddField(
            model_name='player',
            name='tragetsInfo',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='tragetsJson',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='player',
            name='tragetsUpda',
            field=models.IntegerField(default=0),
        ),
    ]
