# Generated by Django 2.0.5 on 2019-04-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_auto_20190430_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='tragetsInfo',
            new_name='targetsInfo',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='tragetsJson',
            new_name='targetsJson',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='tragetsUpda',
            new_name='targetsUpda',
        ),
    ]
