# Generated by Django 2.0.5 on 2019-05-01 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_auto_20190430_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='targetsInfo',
            new_name='targetInfo',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='targetsJson',
            new_name='targetJson',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='targetsUpda',
            new_name='targetUpda',
        ),
    ]
