# Generated by Django 2.0.5 on 2019-05-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_auto_20190501_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='factionAA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='factionId',
            field=models.IntegerField(default=0),
        ),
    ]
