# Generated by Django 2.0.5 on 2019-05-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0010_auto_20190505_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='factionNa',
            field=models.CharField(default='My Faction', max_length=32),
        ),
    ]
