# Generated by Django 2.0.7 on 2019-06-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0012_player_lastactionts'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Update', max_length=16)),
                ('text', models.TextField()),
                ('timestamp', models.IntegerField(default=1560950106.483)),
                ('player', models.ManyToManyField(to='player.Player')),
            ],
        ),
    ]
