# Generated by Django 2.0.7 on 2019-06-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0013_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='authorId',
            field=models.IntegerField(default=2000607),
        ),
        migrations.AddField(
            model_name='news',
            name='authorName',
            field=models.CharField(default='Kivou', max_length=32),
        ),
        migrations.AlterField(
            model_name='news',
            name='player',
            field=models.ManyToManyField(blank=True, to='player.Player'),
        ),
        migrations.AlterField(
            model_name='news',
            name='timestamp',
            field=models.IntegerField(default=1560957465),
        ),
    ]
