# Generated by Django 2.0.7 on 2019-06-19 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0014_auto_20190619_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(default='Info', max_length=16),
        ),
    ]
