# Generated by Django 2.0.5 on 2019-07-23 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0015_auto_20190619_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('B', 'bazaar'), ('F', 'faction'), ('T', 'target'), ('A', 'awards')], default='B', max_length=16)),
                ('text', models.TextField()),
                ('authorId', models.IntegerField(default=2000607)),
                ('authorName', models.CharField(default='Kivou', max_length=32)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
