# Generated by Django 2.0.7 on 2019-07-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0016_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='section',
            field=models.CharField(choices=[('B', 'bazaar'), ('F', 'faction'), ('T', 'target'), ('A', 'awards'), ('S', 'stock')], default='B', max_length=16),
        ),
    ]
