# Generated by Django 2.0.7 on 2019-07-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0017_auto_20190725_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='stocksInfo',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='stocksJson',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='player',
            name='stocksUpda',
            field=models.IntegerField(default=0),
        ),
    ]
