# Generated by Django 2.0.5 on 2019-10-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0019_auto_20190930_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='section',
            field=models.CharField(choices=[('B', 'bazaar'), ('F', 'faction'), ('T', 'target'), ('A', 'awards'), ('S', 'stock'), ('L', 'loot')], default='B', max_length=16),
        ),
    ]
