# Generated by Django 2.0.5 on 2019-10-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0020_auto_20191005_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='awardsRank',
            field=models.IntegerField(default=99999),
        ),
        migrations.AddField(
            model_name='player',
            name='awardsScor',
            field=models.IntegerField(default=0),
        ),
    ]
