# Generated by Django 2.0.5 on 2019-10-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0021_auto_20191024_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=512)),
            ],
        ),
    ]
