# Generated by Django 2.0.5 on 2019-10-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0022_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nTotal', models.IntegerField(default=1)),
                ('nValid', models.IntegerField(default=0)),
                ('nInval', models.IntegerField(default=0)),
                ('nPrune', models.IntegerField(default=0)),
                ('nInact', models.IntegerField(default=0)),
            ],
        ),
    ]
