# Generated by Django 2.2.6 on 2019-11-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0024_auto_20191029_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dId',
            field=models.IntegerField(default=0),
        ),
    ]
