# Generated by Django 2.0 on 2019-11-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0025_player_did'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='dId',
            field=models.BigIntegerField(default=0),
        ),
    ]
