# Generated by Django 3.0.1 on 2019-12-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0028_player_botperm'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='activateNotifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='notifications',
            field=models.TextField(default='{}'),
        ),
    ]
