# Generated by Django 3.0.1 on 2020-01-18 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0029_auto_20191227_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='key',
            new_name='apikey',
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SlugField(default='aaaa', max_length=16)),
                ('lastPulled', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
            ],
        ),
    ]
