# Generated by Django 3.0.1 on 2020-01-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0030_auto_20200118_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='tId',
            field=models.IntegerField(default=0),
        ),
    ]
