# Generated by Django 3.0.1 on 2020-01-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0032_auto_20200123_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='reason',
            field=models.CharField(default='-', max_length=32),
        ),
    ]
