# Generated by Django 3.0.1 on 2020-01-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0033_key_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='section',
            field=models.CharField(choices=[('B', 'bazaar'), ('F', 'factionV2'), ('C', 'faction'), ('T', 'target'), ('A', 'awards'), ('S', 'stock'), ('L', 'loot')], default='B', max_length=16),
        ),
    ]
