# Generated by Django 3.0.1 on 2020-02-24 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0035_player_attacksupda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='apikey',
        ),
    ]
