# Generated by Django 3.0.1 on 2020-03-24 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0037_auto_20200303_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='targetJson',
        ),
        migrations.RemoveField(
            model_name='player',
            name='targetUpda',
        ),
    ]
