# Generated by Django 3.0.4 on 2020-03-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0038_auto_20200324_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factionId', models.IntegerField(default=0)),
                ('spinner', models.CharField(blank=True, default='', max_length=64, null=True)),
            ],
        ),
    ]
