# Generated by Django 3.0.4 on 2020-04-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0040_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='short_error',
            field=models.CharField(default='-', max_length=128),
        ),
    ]
