# Generated by Django 3.0.4 on 2020-04-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0041_auto_20200424_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainFull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(default=0)),
                ('timestamp', models.IntegerField(default=0)),
                ('time_diff', models.IntegerField(default=0)),
                ('happy_before', models.IntegerField(default=0)),
                ('happy_after', models.IntegerField(default=0)),
                ('happy_delta', models.IntegerField(default=0)),
                ('energy_used', models.IntegerField(default=0)),
                ('stat_type', models.CharField(default='None', max_length=16)),
                ('stat_before', models.FloatField(default=0.0)),
                ('stat_after', models.FloatField(default=0.0)),
                ('stat_delta', models.FloatField(default=0.0)),
                ('gym_id', models.IntegerField(default=1)),
                ('gym_dot', models.IntegerField(default=0)),
                ('perks_faction', models.IntegerField(default=0)),
                ('perks_property', models.IntegerField(default=0)),
                ('perks_education_stat', models.IntegerField(default=0)),
                ('perks_education_all', models.IntegerField(default=0)),
                ('perks_company', models.IntegerField(default=0)),
                ('perks_company_happy_red', models.IntegerField(default=0)),
            ],
        ),
    ]
