# Generated by Django 3.0.4 on 2020-05-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0042_trainfull'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainfull',
            name='player_id',
        ),
        migrations.AddField(
            model_name='trainfull',
            name='id_key',
            field=models.SlugField(default='x'),
        ),
    ]
