# Generated by Django 3.0.4 on 2020-05-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0044_auto_20200504_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainfull',
            name='single_train',
            field=models.IntegerField(default=False),
        ),
    ]
