# Generated by Django 3.0.4 on 2020-05-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0046_trainfull_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainfull',
            name='id_key',
            field=models.CharField(default='x', max_length=32),
        ),
    ]
