# Generated by Django 3.0.4 on 2020-05-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0049_auto_20200505_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='awardsRank',
        ),
    ]
