# Generated by Django 3.0.4 on 2020-05-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0051_player_revivesupda'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='awardsPinn',
            field=models.CharField(default='[]', max_length=32),
        ),
    ]
