# Generated by Django 3.0.4 on 2020-05-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0053_tmpreq'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdata',
            name='uidBan',
            field=models.TextField(default='[]'),
        ),
    ]
