# Generated by Django 3.0.8 on 2020-08-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0055_remove_player_botperm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='reason',
            field=models.CharField(default='-', max_length=64),
        ),
    ]
