# Generated by Django 3.0.8 on 2020-09-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0056_auto_20200818_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='factionNa',
            field=models.CharField(default='My Faction', max_length=64),
        ),
    ]
