# Generated by Django 3.1.1 on 2020-09-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0058_auto_20200915_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='value',
            field=models.SlugField(default='aaaa', max_length=30),
        ),
    ]
