# Generated by Django 3.1.1 on 2020-09-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0059_auto_20200915_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='value',
            field=models.SlugField(default='aaaa', max_length=32),
        ),
    ]
