# Generated by Django 3.1.1 on 2020-10-01 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0058_error_fixed'),
        ('player', '0060_auto_20200915_1233'),
    ]

    operations = [
    ]
