# Generated by Django 3.1.2 on 2020-11-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0061_merge_20201001_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='companyDi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='companyId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='companyNa',
            field=models.CharField(default='My Company', max_length=64),
        ),
        migrations.AddField(
            model_name='player',
            name='companyTy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='wend',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='wint',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='wman',
            field=models.IntegerField(default=0),
        ),
    ]
