# Generated by Django 3.1.2 on 2020-11-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0062_auto_20201117_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='section',
            field=models.CharField(choices=[('B', 'bazaar'), ('F', 'faction'), ('T', 'target'), ('A', 'awards'), ('S', 'stock'), ('C', 'company'), ('L', 'loot')], default='B', max_length=16),
        ),
    ]
