# Generated by Django 3.1.2 on 2021-01-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0064_auto_20210104_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='section',
            field=models.CharField(choices=[('all', 'all'), ('home', 'home'), ('bazaar', 'bazaar'), ('faction', 'faction'), ('target', 'target'), ('awards', 'awards'), ('stock', 'stock'), ('company', 'company'), ('loot', 'loot')], default='B', max_length=16),
        ),
    ]
