# Generated by Django 3.1.2 on 2021-01-08 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0065_auto_20210104_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spinner',
        ),
        migrations.RemoveField(
            model_name='playerdata',
            name='ipsBan',
        ),
        migrations.RemoveField(
            model_name='playerdata',
            name='uidBan',
        ),
    ]
