# Generated by Django 3.1.2 on 2021-01-08 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0066_auto_20210108_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='authorId',
        ),
        migrations.RemoveField(
            model_name='message',
            name='authorName',
        ),
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
    ]
