# Generated by Django 3.1.5 on 2021-01-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0068_auto_20210108_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='level',
            field=models.CharField(choices=[('notice', 'notice'), ('warning', 'warning'), ('error', 'error')], default='notice', max_length=16),
        ),
        migrations.AlterField(
            model_name='message',
            name='section',
            field=models.CharField(choices=[('all', 'all'), ('player', 'player'), ('bazaar', 'bazaar'), ('faction', 'faction'), ('target', 'target'), ('awards', 'awards'), ('stock', 'stock'), ('company', 'company'), ('loot', 'loot')], default='all', max_length=16),
        ),
    ]
