# Generated by Django 3.1.7 on 2021-04-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0069_auto_20210112_1032'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['dId'], name='player_play_dId_7ed837_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['id'], name='player_play_id_f21ab6_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['tId'], name='player_play_tId_84e9f3_idx'),
        ),
    ]
