# Generated by Django 3.1.5 on 2021-06-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0069_auto_20210112_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='bazaarJson',
            new_name='bazaarInve',
        ),
        migrations.AddField(
            model_name='player',
            name='bazaarList',
            field=models.TextField(default='[]'),
        ),
    ]
