# Generated by Django 3.1.5 on 2021-06-16 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0070_auto_20210616_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='bazaarInve',
        ),
    ]
