# Generated by Django 3.1.5 on 2021-06-16 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0071_remove_player_bazaarinve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='bazaarUpda',
        ),
    ]
