# Generated by Django 4.0.2 on 2022-03-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0073_auto_20210714_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='access_type',
            field=models.CharField(default='unkown', max_length=64),
        ),
    ]
