# Generated by Django 4.0.2 on 2022-03-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0074_key_access_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainFull',
        ),
        migrations.AddField(
            model_name='key',
            name='access_level',
            field=models.IntegerField(default=0),
        ),
    ]
