# Generated by Django 4.0.2 on 2022-03-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0075_delete_trainfull_key_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='key_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='key',
            name='access_type',
            field=models.CharField(default='Unkown', max_length=64),
        ),
    ]
