# Generated by Django 4.0.2 on 2022-03-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0076_player_key_level_alter_key_access_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='key_last_code',
            field=models.IntegerField(default=0),
        ),
    ]
