# Generated by Django 4.1.5 on 2023-01-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0077_player_key_last_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="key",
            name="value",
            field=models.SlugField(max_length=32, unique=True),
        ),
    ]
