# Generated by Django 2.0.5 on 2019-10-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='error',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='tName',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
