# Generated by Django 3.1.1 on 2020-10-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_auto_20200915_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
