# Generated by Django 3.1.2 on 2020-11-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_auto_20201001_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_section', models.CharField(max_length=32)),
                ('report_period', models.CharField(max_length=32)),
                ('report_timestamp', models.IntegerField(default=0)),
                ('total_requests', models.IntegerField(default=0)),
                ('valid_requests', models.IntegerField(default=0)),
                ('failed_requests', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('bandwidth', models.IntegerField(default=0)),
                ('visitors_metadata', models.TextField(default='{}')),
                ('visitors_data', models.TextField(default='[]')),
                ('requests_metadata', models.TextField(default='{}')),
                ('requests_data', models.TextField(default='[]')),
            ],
        ),
    ]
