# Generated by Django 3.1.2 on 2020-11-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_auto_20201108_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='last_update',
            field=models.IntegerField(default=0),
        ),
    ]
