# Generated by Django 3.1.2 on 2020-12-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_paypal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypal',
            name='signature',
            field=models.CharField(max_length=64),
        ),
    ]
