# Generated by Django 3.1.2 on 2020-12-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0010_auto_20201227_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Droplet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=32)),
                ('token', models.CharField(max_length=32)),
            ],
        ),
    ]
