# Generated by Django 3.1.2 on 2020-12-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0011_droplet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droplet',
            name='endpoint',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='droplet',
            name='token',
            field=models.CharField(max_length=64),
        ),
    ]
