# Generated by Django 3.1.2 on 2020-12-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0012_auto_20201227_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=0)),
                ('paypal_balance', models.CharField(max_length=16)),
                ('paypal_currency', models.CharField(max_length=16)),
                ('droplet_account_balance', models.CharField(max_length=16)),
                ('droplet_month_to_date_usage', models.CharField(max_length=16)),
                ('droplet_month_to_date_balance', models.CharField(max_length=16)),
            ],
        ),
    ]
