# Generated by Django 3.1.2 on 2020-12-27 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0013_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropletSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropletid', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=32)),
                ('vpc_uuid', models.CharField(max_length=32)),
                ('image', models.TextField(default='{}')),
                ('size', models.TextField(default='{}')),
                ('droplet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.droplet')),
            ],
        ),
    ]
