# Generated by Django 3.1.2 on 2020-12-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0015_auto_20201227_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropletspec',
            name='vcpu',
        ),
        migrations.AddField(
            model_name='dropletspec',
            name='vcpus',
            field=models.CharField(default='vcpus', max_length=32),
        ),
    ]
