# Generated by Django 3.1.2 on 2020-12-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0016_auto_20201227_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropletspec',
            name='timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
