# Generated by Django 3.1.2 on 2021-01-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0018_auto_20201227_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='droplet_month_cost',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='balance',
            name='droplet_account_balance',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='balance',
            name='droplet_month_to_date_balance',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='balance',
            name='droplet_month_to_date_usage',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='balance',
            name='paypal_balance',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='balance',
            name='paypal_currency',
            field=models.CharField(default='0', max_length=16),
        ),
    ]
