# Generated by Django 4.0.5 on 2022-10-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0020_apicalllog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disabled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targets', models.BooleanField(default=False)),
            ],
        ),
    ]
