# Generated by Django 4.0.5 on 2022-10-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0021_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='disabled',
            name='disable_load15_threshold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disabled',
            name='disable_load1_threshold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disabled',
            name='disable_load5_threshold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disabled',
            name='enable_load15_threshold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disabled',
            name='enable_load1_threshold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disabled',
            name='enable_load5_threshold',
            field=models.IntegerField(default=0),
        ),
    ]
