# Generated by Django 4.0.5 on 2022-10-30 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0022_disabled_disable_load15_threshold_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disabled',
            old_name='targets',
            new_name='status',
        ),
    ]
