# Generated by Django 4.0.5 on 2024-02-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0023_rename_targets_disabled_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analytics',
        ),
        migrations.DeleteModel(
            name='ApiCallLog',
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
        migrations.DeleteModel(
            name='Disabled',
        ),
        migrations.RemoveField(
            model_name='dropletspec',
            name='droplet',
        ),
        migrations.DeleteModel(
            name='PayPal',
        ),
        migrations.DeleteModel(
            name='Droplet',
        ),
        migrations.DeleteModel(
            name='DropletSpec',
        ),
    ]
