d = {

    # activity
    "daysbeendonator": {"category": "activity", "sub": "default", "type": "integer", "name": "days being a donator"},
    "useractivity": {"category": "activity", "sub": "default", "type": "time", "name": "User activity"},
    "logins": {"category": "activity", "sub": "logins", "type": "integer", "name": "logins"},
    "timesloggedin": {"category": "activity", "sub": "logins", "type": "integer", "name": "Times logged in"},
    "activestreak": {"category": "activity", "sub": "logins", "type": "integer", "name": "active streak"},
    "bestactivestreak": {"category": "activity", "sub": "logins", "type": "integer", "name": "best active streak"},
    "mailssent": {"category": "activity", "sub": "mails", "type": "integer", "name": "mails sent"},
    "friendmailssent": {"category": "activity", "sub": "mails", "type": "integer", "name": "mails sent to friend"},
    "factionmailssent": {"category": "activity", "sub": "mails", "type": "integer", "name": "mails sent to faction"},
    "companymailssent": {"category": "activity", "sub": "mails", "type": "integer", "name": "mails sent to company"},
    "spousemailssent": {"category": "activity", "sub": "mails", "type": "integer", "name": "mails sent to spouse"},
    "itemssent": {"category": "activity", "sub": "default", "type": "integer", "name": "items sent"},

    # money
    "networth": {"category": "money", "sub": "networth", "type": "money", "name": "total"},
    "networthwallet": {"category": "money", "sub": "networth", "type": "money", "name": "wallet"},
    "networthbank": {"category": "money", "sub": "networth", "type": "money", "name": "bank"},
    "networthpoints": {"category": "money", "sub": "networth", "type": "money", "name": "points"},
    "networthitems": {"category": "money", "sub": "networth", "type": "money", "name": "items"},
    "networthdisplaycase": {"category": "money", "sub": "networth", "type": "money", "name": "display case"},
    "networthbazaar": {"category": "money", "sub": "networth", "type": "money", "name": "bazaar"},
    "networthproperties": {"category": "money", "sub": "networth", "type": "money", "name": "properties"},
    "networthstockmarket": {"category": "money", "sub": "networth", "type": "money", "name": "stock market"},
    "networthauctionhouse": {"category": "money", "sub": "networth", "type": "money", "name": "auction house"},
    "networthpending": {"category": "money", "sub": "networth", "type": "money", "name": "pending"},
    "networthcayman": {"category": "money", "sub": "networth", "type": "money", "name": "cayman"},
    "networthvault": {"category": "money", "sub": "networth", "type": "money", "name": "vault"},
    "networthcompany": {"category": "money", "sub": "networth", "type": "money", "name": "company"},
    "networthbookie": {"category": "money", "sub": "networth", "type": "money", "name": "bookie"},
    "networthloan": {"category": "money", "sub": "networth", "type": "money", "name": "loan"},
    "networthunpaidfees": {"category": "money", "sub": "networth", "type": "money", "name": "unpaid fees"},
    "networthpiggybank": {"category": "money", "sub": "networth", "type": "money", "name": "piggy bank"},
    "networthitemmarket": {"category": "money", "sub": "networth", "type": "money", "name": "item market"},
    "moneyinvested": {"category": "money", "sub": "default", "type": "money", "name": "money invested"},
    "investedprofit": {"category": "money", "sub": "default", "type": "money", "name": "invested profits"},
    "stockpayouts": {"category": "money", "sub": "stocks", "type": "integer", "name": "stock payouts"},
    "stockprofits": {"category": "money", "sub": "stocks", "type": "money", "name": "stock profits"},
    "stocklosses": {"category": "money", "sub": "stocks", "type": "money", "name": "stock losses"},
    "stockfees": {"category": "money", "sub": "stocks", "type": "money", "name": "stock fees"},

    # attacks
    "elo": {"category": "attacks", "sub": "default", "type": "integer", "name": "elo"},
    "itemslooted": {"category": "attacks", "sub": "default", "type": "integer", "name": "items looted"},
    "attackcriticalhits": {"category": "attacks", "sub": "Hits", "type": "integer", "name": "critical"},
    "attackhits": {"category": "attacks", "sub": "Hits", "type": "integer", "name": "hits"},
    "attackmisses": {"category": "attacks", "sub": "Hits", "type": "integer", "name": "misses"},
    "bestdamage": {"category": "attacks", "sub": "Hits", "type": "integer", "name": "best damage"},
    "attackdamage": {"category": "attacks", "sub": "Hits", "type": "integer", "name": "damage made"},
    "yourunaway": {"category": "attacks", "sub": "default", "type": "integer", "name": "runaway"},
    "attacksdraw": {"category": "attacks", "sub": "default", "type": "integer", "name": "draw"},
    "attacksassisted": {"category": "attacks", "sub": "default", "type": "integer", "name": "assisted"},
    "attackslost": {"category": "attacks", "sub": "default", "type": "integer", "name": "lost"},
    "onehitkills": {"category": "attacks", "sub": "default", "type": "integer", "name": "one hit kills"},
    "attackswon": {"category": "attacks", "sub": "default", "type": "integer", "name": "won"},
    "attacksstealthed": {"category": "attacks", "sub": "default", "type": "integer", "name": "stealthed"},
    "unarmoredwon": {"category": "attacks", "sub": "default", "type": "integer", "name": "unarmored won"},
    "highestbeaten": {"category": "attacks", "sub": "default", "type": "integer", "name": "highest level beaten"},
    "defendslost": {"category": "attacks", "sub": "defends", "type": "integer", "name": "lost"},
    "defendswon": {"category": "attacks", "sub": "defends", "type": "integer", "name": "won"},
    "defendsstalemated": {"category": "attacks", "sub": "defends", "type": "integer", "name": "stalemated"},
    "theyrunaway": {"category": "attacks", "sub": "defends", "type": "integer", "name": "runaway"},
    "killstreak": {"category": "attacks", "sub": "kill streak", "type": "integer", "name": "current kill streak"},
    "bestkillstreak": {"category": "attacks", "sub": "kill streak", "type": "integer", "name": "best kill streak"},
    "moneymugged": {"category": "attacks", "sub": "mug", "type": "money", "name": "money mugged"},
    "largestmug": {"category": "attacks", "sub": "mug", "type": "money", "name": "largest mug"},
    "roundsfired": {"category": "attacks", "sub": "Rounds", "type": "integer", "name": "rounds fired"},
    "specialammoused": {"category": "attacks", "sub": "Rounds", "type": "integer", "name": "special ammo"},
    "hollowammoused": {"category": "attacks", "sub": "Rounds", "type": "integer", "name": "hollow ammo"},
    "tracerammoused": {"category": "attacks", "sub": "Rounds", "type": "integer", "name": "tracer ammo"},
    "incendiaryammoused": {"category": "attacks", "sub": "Rounds", "type": "integer", "name": "incendiary ammo"},
    "piercingammoused": {"category": "attacks", "sub": "Rounds", "type": "integer", "name": "piercing ammo"},
    "piehits": {"category": "attacks", "sub": "final hits", "type": "integer", "name": "piercing weapons"},
    "axehits": {"category": "attacks", "sub": "final hits", "type": "integer", "name": "clubbing weapons"},
    "chahits": {"category": "attacks", "sub": "final hits", "type": "integer", "name": "mechanical guns"},
    "rifhits": {"category": "attacks", "sub": "final hits", "type": "integer", "name": "rifles"},
    "pishits": {"category": "attacks", "sub": "final hits", "type": "integer", "name": "pistols"},
    "grehits": {"category": "attacks", "sub": "final hits", "type": "integer", "name": "temporary weapons"},
    "smghits": {"category": "attacks", "sub": "final hits", "type": "integer", "name": "sub machine guns"},
    "heahits": {"category": "attacks", "sub": "final hits", "type": "integer", "name": "heavy artillery"},
    "shohits": {"category": "attacks", "sub": "final hits", "type": "integer", "name": "shotguns"},
    "slahits": {"category": "attacks", "sub": "final hits", "type": "integer", "name": "slashing weapons"},
    "h2hhits": {"category": "attacks", "sub": "final hits", "type": "integer", "name": "hand to hand"},
    "machits": {"category": "attacks", "sub": "final hits", "type": "integer", "name": "machine guns"},
    "strength": {"category": "attacks", "sub": "battle stats", "type": "integer", "name": "strength"},
    "defense": {"category": "attacks", "sub": "battle stats", "type": "integer", "name": "defense"},
    "speed": {"category": "attacks", "sub": "battle stats", "type": "integer", "name": "speed"},
    "dexterity": {"category": "attacks", "sub": "battle stats", "type": "integer", "name": "dexterity"},
    "totalstats": {"category": "attacks", "sub": "battle stats", "type": "integer", "name": "total"},

    # bounties
    "bountiesplaced": {"category": "bounties", "sub": "default", "type": "integer", "name": "placed"},
    "bountiesreceived": {"category": "bounties", "sub": "default", "type": "integer", "name": "received"},
    "bountiescollected": {"category": "bounties", "sub": "default", "type": "integer", "name": "collected"},
    "totalbountyspent": {"category": "bounties", "sub": "default", "type": "money", "name": "total spent"},
    "totalbountyreward": {"category": "bounties", "sub": "default", "type": "money", "name": "total reward"},
    "receivedbountyvalue": {"category": "bounties", "sub": "default", "type": "money", "name": "received value"},

    # missions
    "missioncreditsearned": {"category": "Missions", "sub": "default", "type": "integer", "name": "credits earned"},
    "contractscompleted": {"category": "Missions", "sub": "default", "type": "integer", "name": "contracts completed"},
    "dukecontractscompleted": {"category": "Missions", "sub": "default", "type": "integer", "name": "duke contracts completed"},
    "missionscompleted": {"category": "Missions", "sub": "default", "type": "integer", "name": "missions completed"},

    # jail
    "jailed": {"category": "jail", "sub": "default", "type": "integer", "name": "times jailed"},
    "failedbusts": {"category": "jail", "sub": "busts", "type": "integer", "name": "failed busts"},
    "peoplebusted": {"category": "jail", "sub": "busts", "type": "integer", "name": "people busted"},
    "peoplebought": {"category": "jail", "sub": "bails", "type": "integer", "name": "people bought"},
    "peopleboughtspent": {"category": "jail", "sub": "bails", "type": "money", "name": "money spent"},

    # drugs
    "drugsused": {"category": "drugs", "sub": "default", "type": "integer", "name": "used"},
    "overdosed": {"category": "drugs", "sub": "default", "type": "integer", "name": "overdosed"},
    "xantaken": {"category": "drugs", "sub": "taken", "type": "integer", "name": "xanax"},
    "cantaken": {"category": "drugs", "sub": "taken", "type": "integer", "name": "canabis"},
    "victaken": {"category": "drugs", "sub": "taken", "type": "integer", "name": "vicodin"},
    "exttaken": {"category": "drugs", "sub": "taken", "type": "integer", "name": "ecstasy"},
    "lsdtaken": {"category": "drugs", "sub": "taken", "type": "integer", "name": "lsd"},
    "shrtaken": {"category": "drugs", "sub": "taken", "type": "integer", "name": "mushroom"},
    "kettaken": {"category": "drugs", "sub": "taken", "type": "integer", "name": "ketamin"},
    "opitaken": {"category": "drugs", "sub": "taken", "type": "integer", "name": "opium"},
    "pcptaken": {"category": "drugs", "sub": "taken", "type": "integer", "name": "pcp"},
    "spetaken": {"category": "drugs", "sub": "taken", "type": "integer", "name": "speed"},
    "rehabs": {"category": "drugs", "sub": "rehab", "type": "integer", "name": "times"},
    "rehabcost": {"category": "drugs", "sub": "rehab", "type": "money", "name": "cost"},

    # trader
    "bazaarcustomers": {"category": "trader", "sub": "bazaar", "type": "integer", "name": "bazaar customers"},
    "bazaarsales": {"category": "trader", "sub": "bazaar", "type": "integer", "name": "bazaar sales"},
    "bazaarprofit": {"category": "trader", "sub": "bazaar", "type": "money", "name": "bazaar profit"},
    "trades": {"category": "trader", "sub": "default", "type": "integer", "name": "trades"},
    "auctionsells": {"category": "trader", "sub": "auction", "type": "integer", "name": "sells"},
    "auctionswon": {"category": "trader", "sub": "auction", "type": "integer", "name": "won"},
    "pointsbought": {"category": "trader", "sub": "points", "type": "integer", "name": "bought"},
    "pointssold": {"category": "trader", "sub": "points", "type": "integer", "name": "sold"},
    "weaponsbought": {"category": "trader", "sub": "bought", "type": "integer", "name": "weapons"},
    "itemsbought": {"category": "trader", "sub": "bought", "type": "integer", "name": "items"},
    "cityitemsbought": {"category": "trader", "sub": "bought", "type": "integer", "name": "city items"},

    # travel
    "mextravel": {"category": "travel", "sub": "destination", "type": "integer", "name": "mexico"},
    "hawtravel": {"category": "travel", "sub": "destination", "type": "integer", "name": "hawaii"},
    "argtravel": {"category": "travel", "sub": "destination", "type": "integer", "name": "argentina"},
    "dubtravel": {"category": "travel", "sub": "destination", "type": "integer", "name": "uae"},
    "cantravel": {"category": "travel", "sub": "destination", "type": "integer", "name": "canada"},
    "lontravel": {"category": "travel", "sub": "destination", "type": "integer", "name": "uk"},
    "caytravel": {"category": "travel", "sub": "destination", "type": "integer", "name": "cayman"},
    "chitravel": {"category": "travel", "sub": "destination", "type": "integer", "name": "china"},
    "switravel": {"category": "travel", "sub": "destination", "type": "integer", "name": "switzerland"},
    "soutravel": {"category": "travel", "sub": "destination", "type": "integer", "name": "south africa"},
    "japtravel": {"category": "travel", "sub": "destination", "type": "integer", "name": "japan"},
    "traveltimes": {"category": "travel", "sub": "default", "type": "integer", "name": "Times"},
    "traveltime": {"category": "travel", "sub": "default", "type": "time", "name": "Days flying"},
    "itemsboughtabroad": {"category": "travel", "sub": "default", "type": "integer", "name": "items bought abroad"},
    "attackswonabroad": {"category": "travel", "sub": "attacks", "type": "integer", "name": "attacks won abroad"},
    "defendslostabroad": {"category": "travel", "sub": "attacks", "type": "integer", "name": "defends lost abroad"},

    # medical
    "hospital": {"category": "medical", "sub": "default", "type": "integer", "name": "times in hospital"},
    "medstolen": {"category": "medical", "sub": "default", "type": "integer", "name": "items stolen"},
    "medicalitemsused": {"category": "medical", "sub": "default", "type": "integer", "name": "items used"},
    "revivesreceived": {"category": "medical", "sub": "default", "type": "integer", "name": "revives received"},
    "revives": {"category": "medical", "sub": "default", "type": "integer", "name": "revives made"},
    "bloodwithdrawn": {"category": "medical", "sub": "default", "type": "integer", "name": "blood withdrawn"},

    # refills
    "nerverefills": {"category": "refill", "sub": "default", "type": "integer", "name": "nerve"},
    "tokenrefills": {"category": "refill", "sub": "default", "type": "integer", "name": "casino token"},
    "refills": {"category": "refill", "sub": "default", "type": "integer", "name": "energy"},

    # faction
    "territorytime": {"category": "faction", "sub": "territories", "type": "time", "name": "territory time"},
    "territoryjoins": {"category": "faction", "sub": "territories", "type": "integer", "name": "territory joins"},
    "organisedcrimes": {"category": "faction", "sub": "default", "type": "integer", "name": "organised crimes"},
    "respectforfaction": {"category": "faction", "sub": "default", "type": "integer", "name": "respect earned"},
    "retals": {"category": "faction", "sub": "default", "type": "integer", "name": "retals made"},

    # racing
    "racingpointsearned": {"category": "racing", "sub": "default", "type": "integer", "name": "points earned"},
    "raceswon": {"category": "racing", "sub": "default", "type": "integer", "name": "races won"},
    "racesentered": {"category": "racing", "sub": "default", "type": "integer", "name": "races entered"},
    "racingskill": {"category": "racing", "sub": "default", "type": "float", "name": "racing skill"},
    "networthenlistedcars": {"category": "racing", "sub": "default", "type": "money", "name": "networth enlisted cars"},

    # item
    "consumablesused": {"category": "item used", "sub": "default", "type": "integer", "name": "consumable"},
    "alcoholused": {"category": "item used", "sub": "default", "type": "integer", "name": "alcohol"},
    "candyused": {"category": "item used", "sub": "default", "type": "integer", "name": "candy"},
    "energydrinkused": {"category": "item used", "sub": "default", "type": "integer", "name": "energy drink"},
    "boostersused": {"category": "item used", "sub": "default", "type": "integer", "name": "boosters"},
    "booksread": {"category": "item used", "sub": "default", "type": "integer", "name": "books"},
    "statenhancersused": {"category": "item used", "sub": "default", "type": "integer", "name": "stat enhancer"},

    # misc
    "awards": {"category": "misc", "sub": "default", "type": "integer", "name": "awards"},
    "reviveskill": {"category": "misc", "sub": "default", "type": "integer", "name": "revive skill"},
    "virusescoded": {"category": "misc", "sub": "default", "type": "integer", "name": "viruses coded"},
    "itemsdumped": {"category": "misc", "sub": "city", "type": "integer", "name": "items dumped"},
    "dumpsearches": {"category": "misc", "sub": "city", "type": "integer", "name": "dump searches"},
    "dumpfinds": {"category": "misc", "sub": "city", "type": "integer", "name": "dump finds"},
    "cityfinds": {"category": "misc", "sub": "city", "type": "integer", "name": "city finds"},
    "meritsbought": {"category": "misc", "sub": "default", "type": "integer", "name": "merits bought"},
    "personalsplaced": {"category": "misc", "sub": "default", "type": "integer", "name": "personal ads"},
    "classifiedadsplaced": {"category": "misc", "sub": "default", "type": "integer", "name": "classified ads"},
    "spydone": {"category": "misc", "sub": "default", "type": "integer", "name": "spy done"},
    "arrestsmade": {"category": "misc", "sub": "default", "type": "integer", "name": "arrests made"},
    "trainsreceived": {"category": "misc", "sub": "work", "type": "integer", "name": "trains received"},
    "jobpointsused": {"category": "misc", "sub": "work", "type": "integer", "name": "job points used"},
    "manuallabor": {"category": "misc", "sub": "work", "type": "integer", "name": "manual labor"},
    "intelligence": {"category": "misc", "sub": "work", "type": "integer", "name": "intelligence"},
    "endurance": {"category": "misc", "sub": "work", "type": "integer", "name": "endurance"},
    "totalworkingstats": {"category": "misc", "sub": "work", "type": "integer", "name": "total working stats"},


}
