# Generated by Django 2.0.5 on 2018-09-10 08:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Duke', max_length=200)),
                ('hit', models.IntegerField(default=0)),
                ('respect', models.IntegerField(default=0)),
                ('respectMax', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tId', models.IntegerField(default=0, unique=True)),
                ('nHits', models.IntegerField(default=0)),
                ('respect', models.FloatField(default=0)),
                ('start', models.IntegerField(default=0)),
                ('startDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.IntegerField(default=0)),
                ('endDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
                ('jointReport', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attackerId', models.IntegerField(default=0)),
                ('name', models.CharField(default='Duke', max_length=200)),
                ('hits', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('respect', models.FloatField(default=0)),
                ('respectTotal', models.FloatField(default=0)),
                ('daysInFaction', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tId', models.IntegerField(default=0, unique=True)),
                ('name', models.CharField(default='MyFaction', max_length=200)),
                ('hitsThreshold', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tId', models.IntegerField(default=0, unique=True)),
                ('name', models.CharField(default='Duke', max_length=200)),
                ('daysInFaction', models.IntegerField(default=0)),
                ('lastAction', models.CharField(default='Duke', max_length=200)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chain.Faction')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chain.Chain')),
            ],
        ),
        migrations.AddField(
            model_name='count',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chain.Report'),
        ),
        migrations.AddField(
            model_name='chain',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chain.Faction'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chain.Report'),
        ),
    ]
