# Generated by Django 2.0.5 on 2018-09-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='tId',
            field=models.IntegerField(default=0),
        ),
    ]
