# Generated by Django 2.0.5 on 2018-09-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0003_faction_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='respect',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='respectMax',
            field=models.FloatField(default=0),
        ),
    ]
