# Generated by Django 2.0.5 on 2018-10-07 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0004_auto_20180929_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='count',
            old_name='respectTotal',
            new_name='fairFight',
        ),
    ]
