# Generated by Django 2.1 on 2018-10-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0005_auto_20181007_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='graph',
            field=models.TextField(default=''),
        ),
    ]
