# Generated by Django 2.0.5 on 2018-10-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0006_chain_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='graph',
            field=models.TextField(default='', null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='lastAction',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
