# Generated by Django 2.0.5 on 2018-10-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0008_count_beenthere'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='apiString',
            field=models.CharField(default='0', max_length=330),
        ),
    ]
