# Generated by Django 2.0.5 on 2018-10-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0012_auto_20181031_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='lastUpdate',
            field=models.IntegerField(default=0),
        ),
    ]
