# Generated by Django 2.0.5 on 2018-10-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0014_remove_target_lastupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='lastUpdateTS',
            new_name='lastUpdate',
        ),
        migrations.AddField(
            model_name='target',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='target',
            name='rank',
            field=models.CharField(default='Nub', max_length=15),
        ),
    ]
