# Generated by Django 2.0.5 on 2018-10-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0015_auto_20181031_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='name',
            field=models.CharField(default='Duke', max_length=64),
        ),
        migrations.AlterField(
            model_name='count',
            name='name',
            field=models.CharField(default='Duke', max_length=64),
        ),
        migrations.AlterField(
            model_name='target',
            name='lastAction',
            field=models.CharField(default='Who knows', max_length=64),
        ),
        migrations.AlterField(
            model_name='target',
            name='rank',
            field=models.CharField(default='Nub', max_length=64),
        ),
        migrations.AlterField(
            model_name='target',
            name='result',
            field=models.CharField(default='Poutrage', max_length=64),
        ),
        migrations.AlterField(
            model_name='target',
            name='targetName',
            field=models.CharField(default='Duke', max_length=64),
        ),
    ]
