# Generated by Django 2.0.5 on 2018-11-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0016_auto_20181031_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='nAttacks',
            field=models.IntegerField(default=1),
        ),
    ]
