# Generated by Django 2.0.5 on 2018-11-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0017_chain_nattacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='groupAttack',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='count',
            name='overseas',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='count',
            name='retaliation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='count',
            name='war',
            field=models.FloatField(default=0),
        ),
    ]
