# Generated by Django 2.0.5 on 2018-12-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0020_count_watcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='refreshStatus',
            field=models.BooleanField(default=True),
        ),
    ]
