# Generated by Django 2.0.5 on 2019-02-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0021_target_refreshstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='createReport',
            field=models.BooleanField(default=False),
        ),
    ]
