# Generated by Django 2.0.5 on 2019-02-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0022_chain_createreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='list',
            field=models.IntegerField(default=0),
        ),
    ]
