# Generated by Django 2.0.5 on 2019-04-13 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0023_target_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tss', models.IntegerField(default=0)),
                ('tse', models.IntegerField(default=0)),
                ('req', models.TextField()),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chain.Faction')),
            ],
        ),
    ]
