# Generated by Django 2.0.5 on 2019-04-14 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0024_attacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attacks',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chain.Report'),
        ),
    ]
