# Generated by Django 2.0.5 on 2019-04-14 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0026_auto_20190414_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attacks',
            name='faction',
        ),
        migrations.DeleteModel(
            name='Attacks',
        ),
    ]
