# Generated by Django 2.0.5 on 2019-04-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0029_auto_20190414_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='reportNHits',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chain',
            name='nHits',
            field=models.IntegerField(default=1),
        ),
    ]
