# Generated by Django 2.0.5 on 2019-04-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0032_faction_lastapicall'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='nAPICall',
            field=models.IntegerField(default=2),
        ),
    ]
