# Generated by Django 2.0.5 on 2019-05-06 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0033_faction_napicall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chain',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='chain',
            name='startDate',
        ),
    ]
