# Generated by Django 2.0.5 on 2019-05-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0034_auto_20190506_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowedFactions', models.TextField(default='{}')),
            ],
        ),
    ]
