# Generated by Django 2.0.5 on 2019-05-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0035_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='tId',
            field=models.IntegerField(default=0),
        ),
    ]
