# Generated by Django 2.0.5 on 2019-05-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0036_bonus_tid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crontab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='faction',
            name='crontab',
            field=models.ManyToManyField(to='chain.Crontab'),
        ),
    ]
