# Generated by Django 2.0.5 on 2019-05-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0038_auto_20190512_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='apiString',
            field=models.TextField(default='{}'),
        ),
    ]
