# Generated by Django 2.0.5 on 2019-05-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0039_auto_20190512_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crontab',
            name='faction',
            field=models.ManyToManyField(blank=True, to='chain.Faction'),
        ),
    ]
