# Generated by Django 2.0.5 on 2019-05-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0041_crontab_tabnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='hasReport',
            field=models.BooleanField(default=False),
        ),
    ]
