# Generated by Django 2.0.5 on 2019-05-16 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0042_chain_hasreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='date',
        ),
    ]
