# Generated by Django 2.0.5 on 2019-05-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0043_remove_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
