# Generated by Django 2.0.5 on 2019-05-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0044_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='posterOpt',
            field=models.TextField(default='{}'),
        ),
    ]
