# Generated by Django 2.0.5 on 2019-06-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0047_faction_membersupda'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
    ]
