# Generated by Django 2.0.7 on 2019-06-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0049_faction_numberofkeys'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontab',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
