# Generated by Django 2.0.5 on 2019-06-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0050_crontab_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='armoryRecord',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faction',
            name='armoryString',
            field=models.TextField(default='{}'),
        ),
    ]
