# Generated by Django 2.0.5 on 2019-07-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0051_auto_20190628_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='warhits',
            field=models.IntegerField(default=0),
        ),
    ]
