# Generated by Django 2.0.5 on 2019-08-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0053_faction_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tId', models.IntegerField(default=0)),
                ('tss', models.IntegerField(default=0)),
                ('tse', models.IntegerField(default=0)),
                ('attackers', models.TextField(blank=True, default='{}', null=True)),
                ('defenders', models.TextField(blank=True, default='{}', null=True)),
                ('attackerFactionId', models.IntegerField(default=0)),
                ('attackerFactionName', models.CharField(default='MyFaction', max_length=200)),
                ('territory', models.CharField(default='AAA', max_length=3)),
            ],
        ),
    ]
