# Generated by Django 2.0.5 on 2019-08-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0055_auto_20190829_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='factions',
            field=models.ManyToManyField(blank=True, to='chain.Faction'),
        ),
    ]
