# Generated by Django 2.0.5 on 2019-09-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0058_auto_20190902_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Racket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tId', models.CharField(default='XXX', max_length=3)),
                ('name', models.CharField(default='Racket Name', max_length=200)),
                ('reward', models.CharField(default='Get nice things for free', max_length=200)),
                ('created', models.IntegerField(default=0)),
                ('changed', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('faction', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tId', models.CharField(default='XXX', max_length=3)),
                ('sector', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('density', models.IntegerField(default=0)),
                ('daily_respect', models.IntegerField(default=0)),
                ('coordinate_x', models.FloatField(default=0)),
                ('coordinate_y', models.FloatField(default=0)),
                ('faction', models.IntegerField(default=0)),
                ('racket', models.TextField(blank=True, default='{}', null=True)),
            ],
        ),
    ]
