# Generated by Django 2.0.5 on 2019-10-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0059_racket_territory'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='createLive',
            field=models.BooleanField(default=False),
        ),
    ]
