# Generated by Django 2.0.5 on 2019-10-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0061_wall_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='breakSingleFaction',
            field=models.BooleanField(default=False),
        ),
    ]
