# Generated by Django 2.0.5 on 2019-10-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0062_wall_breaksinglefaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='createReport',
            field=models.IntegerField(default=0),
        ),
    ]
