# Generated by Django 2.0.5 on 2019-10-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0064_auto_20191011_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='wall',
            field=models.BooleanField(default=False),
        ),
    ]
