# Generated by Django 2.0.5 on 2019-10-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0065_chain_wall'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='graphCrit',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
