# Generated by Django 2.0.5 on 2019-10-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0066_chain_graphcrit'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('territoryTS', models.IntegerField(default=0)),
            ],
        ),
    ]
