# Generated by Django 2.0.5 on 2019-10-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0067_factiondata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
