# Generated by Django 2.0 on 2019-11-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0068_delete_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='factiondata',
            name='upgradeTree',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
