# Generated by Django 2.0 on 2019-11-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0069_factiondata_upgradetree'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='factionTree',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='faction',
            name='treeUpda',
            field=models.IntegerField(default=0),
        ),
    ]
