# Generated by Django 2.0 on 2019-11-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0070_auto_20191104_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='simuTree',
            field=models.TextField(default='{}'),
        ),
    ]
