# Generated by Django 2.2.7 on 2019-11-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0072_faction_respect'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='targetName',
            field=models.CharField(default='Unkown', max_length=15),
        ),
        migrations.AddField(
            model_name='bonus',
            name='targetId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='name',
            field=models.CharField(default='Duke', max_length=15),
        ),
        migrations.AlterField(
            model_name='count',
            name='name',
            field=models.CharField(default='Duke', max_length=15),
        ),
        migrations.AlterField(
            model_name='wall',
            name='attackerFactionName',
            field=models.CharField(default='AttackFaction', max_length=15),
        ),
        migrations.AlterField(
            model_name='wall',
            name='defenderFactionName',
            field=models.CharField(default='DefendFaction', max_length=15),
        ),
    ]
