# Generated by Django 2.2.7 on 2019-11-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0073_auto_20191110_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='graphStat',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
