# Generated by Django 2.2.7 on 2019-11-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0074_chain_graphstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='networthString',
            field=models.TextField(default='{}'),
        ),
    ]
