# Generated by Django 2.2.7 on 2019-11-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0075_faction_networthstring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall',
            name='attackerFactionName',
            field=models.CharField(default='AttackFaction', max_length=32),
        ),
        migrations.AlterField(
            model_name='wall',
            name='defenderFactionName',
            field=models.CharField(default='DefendFaction', max_length=32),
        ),
    ]
