# Generated by Django 2.2.7 on 2019-11-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0076_auto_20191125_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='lastActionTS',
            field=models.IntegerField(default=0),
        ),
    ]
