# Generated by Django 2.2.7 on 2019-11-28 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0077_member_lastactionts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=0)),
                ('name', models.CharField(default='stat type', max_length=64)),
                ('type', models.IntegerField(default=0)),
                ('contributors', models.TextField(default='{}')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chain.Faction')),
            ],
        ),
    ]
