# Generated by Django 2.2.7 on 2019-12-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0078_stat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='status',
        ),
        migrations.AddField(
            model_name='member',
            name='arson',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='color',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='member',
            name='description',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='member',
            name='details',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='member',
            name='energy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='nnb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='shareE',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='shareN',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='state',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='member',
            name='until',
            field=models.IntegerField(default=0),
        ),
    ]
