# Generated by Django 2.2.7 on 2019-12-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0079_auto_20191212_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='shareE',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='member',
            name='shareN',
            field=models.IntegerField(default=-1),
        ),
    ]
