# Generated by Django 2.2.7 on 2019-12-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0080_auto_20191212_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='memberStatus',
            field=models.TextField(default='{}'),
        ),
    ]
