# Generated by Django 3.0.1 on 2019-12-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0083_faction_fundsstring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='description',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='member',
            name='details',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
