# Generated by Django 3.0.1 on 2020-01-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0085_revive_revivecontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='revive',
            name='tId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='revivecontract',
            name='computing',
            field=models.BooleanField(default=True),
        ),
    ]
