# Generated by Django 3.0.1 on 2020-01-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0086_auto_20200104_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='revivecontract',
            name='goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revivecontract',
            name='last',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revivecontract',
            name='owner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='revivecontract',
            name='revives',
            field=models.IntegerField(default=0),
        ),
    ]
