# Generated by Django 3.0.1 on 2020-01-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0089_revivecontract_factions'),
    ]

    operations = [
        migrations.AddField(
            model_name='revivecontract',
            name='revivesContract',
            field=models.IntegerField(default=0),
        ),
    ]
