# Generated by Django 3.0.1 on 2020-01-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0090_revivecontract_revivescontract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revivecontract',
            name='factions',
        ),
        migrations.AddField(
            model_name='revivecontract',
            name='factionsRevivers',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='revivecontract',
            name='factionsTargets',
            field=models.TextField(default='[]'),
        ),
    ]
