# Generated by Django 3.0.1 on 2020-01-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0091_auto_20200106_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revivecontract',
            old_name='revives',
            new_name='revivesMade',
        ),
        migrations.AddField(
            model_name='revivecontract',
            name='revivesReceived',
            field=models.IntegerField(default=0),
        ),
    ]
