# Generated by Django 3.0.1 on 2020-01-12 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0093_faction_posterhold'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttacksBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tss', models.IntegerField(default=0)),
                ('tse', models.IntegerField(default=0)),
                ('live', models.BooleanField(default=False)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chain.Faction')),
            ],
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_started', models.IntegerField(default=0)),
                ('timestamp_ended', models.IntegerField(default=0)),
                ('attacker_id', models.IntegerField(default=0)),
                ('attacker_name', models.CharField(default='AttackFaction', max_length=16)),
                ('attacker_faction', models.IntegerField(default=0)),
                ('attacker_factionname', models.CharField(default='AttackFaction', max_length=32)),
                ('defender_id', models.IntegerField(default=0)),
                ('defender_name', models.CharField(default='AttackFaction', max_length=16)),
                ('defender_faction', models.IntegerField(default=0)),
                ('defender_factionname', models.CharField(default='AttackFaction', max_length=32)),
                ('result', models.CharField(default='AttackFaction', max_length=32)),
                ('stealthed', models.IntegerField(default=0)),
                ('respect_gain', models.FloatField(default=0.0)),
                ('chain', models.IntegerField(default=0)),
                ('fairFight', models.FloatField(default=0.0)),
                ('war', models.IntegerField(default=0)),
                ('retaliation', models.FloatField(default=0.0)),
                ('groupAttack', models.FloatField(default=0.0)),
                ('overseas', models.FloatField(default=0.0)),
                ('chainBonus', models.IntegerField(default=0)),
                ('breakdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chain.AttacksBreakdown')),
            ],
        ),
    ]
