# Generated by Django 3.0.1 on 2020-01-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0094_attack_attacksbreakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='tId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attacksbreakdown',
            name='computing',
            field=models.BooleanField(default=True),
        ),
    ]
