# Generated by Django 3.0.1 on 2020-01-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0095_auto_20200112_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='attacker_factionname',
            field=models.CharField(default='attacker_factionname', max_length=32),
        ),
        migrations.AlterField(
            model_name='attack',
            name='attacker_name',
            field=models.CharField(default='attacker_name', max_length=16),
        ),
        migrations.AlterField(
            model_name='attack',
            name='defender_factionname',
            field=models.CharField(blank=True, default='defender_factionname', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='attack',
            name='defender_name',
            field=models.CharField(blank=True, default='defender_name', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='attack',
            name='result',
            field=models.CharField(default='result', max_length=32),
        ),
    ]
