# Generated by Django 3.0.1 on 2020-01-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0096_auto_20200112_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='attacker_factionname',
            field=models.CharField(blank=True, default='attacker_factionname', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='attack',
            name='attacker_name',
            field=models.CharField(blank=True, default='attacker_name', max_length=16, null=True),
        ),
    ]
