# Generated by Django 3.0.1 on 2020-01-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0097_auto_20200112_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacksbreakdown',
            name='attackingFactions',
            field=models.TextField(default='[]'),
        ),
    ]
