# Generated by Django 3.0.1 on 2020-01-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0098_attacksbreakdown_attackingfactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attacksbreakdown',
            old_name='attackingFactions',
            new_name='attackerFactions',
        ),
        migrations.AddField(
            model_name='attacksbreakdown',
            name='defenderFactions',
            field=models.TextField(default='[]'),
        ),
    ]
