# Generated by Django 3.0.1 on 2020-01-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0100_remove_stat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='discordName',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='faction',
            name='name',
            field=models.CharField(default='MyFaction', max_length=32),
        ),
    ]
