# Generated by Django 4.0.5 on 2024-02-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('bot', '0001_initial'), ('bot', '0002_configuration'), ('bot', '0003_auto_20191202_1321'), ('bot', '0004_configuration_name'), ('bot', '0005_configurationhelper'), ('bot', '0006_configurationhelper_guildname'), ('bot', '0007_auto_20191203_1339'), ('bot', '0008_auto_20191203_1444'), ('bot', '0009_guild_managechannels'), ('bot', '0010_guild_stockchannel'), ('bot', '0011_auto_20191212_0002'), ('bot', '0012_auto_20191214_1326'), ('bot', '0013_auto_20191215_1959'), ('bot', '0014_auto_20191216_2220'), ('bot', '0015_guild_stockalerts'), ('bot', '0016_auto_20200107_2258'), ('bot', '0017_auto_20200116_1519'), ('bot', '0018_guild_revivemodule'), ('bot', '0019_chat'), ('bot', '0020_auto_20200204_2254'), ('bot', '0021_auto_20200204_2329'), ('bot', '0022_auto_20200206_2344'), ('bot', '0023_auto_20200206_2356'), ('bot', '0024_auto_20200209_2006'), ('bot', '0025_auto_20200211_1347'), ('bot', '0026_remove_guild_verifyfactions'), ('bot', '0027_guild_verifyfactions'), ('bot', '0028_auto_20200214_1014'), ('bot', '0029_auto_20200214_1017'), ('bot', '0030_guild_systemchannel'), ('bot', '0031_auto_20200220_0838'), ('bot', '0032_auto_20200220_1123'), ('bot', '0033_discordapp_administrators'), ('bot', '0034_auto_20200220_1200'), ('bot', '0035_auto_20200223_1418'), ('bot', '0036_auto_20200223_1458'), ('bot', '0037_auto_20200302_0954'), ('bot', '0038_auto_20200305_1238'), ('bot', '0039_auto_20200305_1244'), ('bot', '0040_auto_20200310_1432'), ('bot', '0041_remove_chat_key'), ('bot', '0042_auto_20200402_0917'), ('bot', '0043_auto_20200405_1902'), ('bot', '0044_auto_20200407_1040'), ('bot', '0045_rackets'), ('bot', '0046_auto_20200407_1928'), ('bot', '0047_auto_20200614_2202'), ('bot', '0048_auto_20200619_1229'), ('bot', '0049_bot_server'), ('bot', '0050_auto_20200629_1442'), ('bot', '0051_server_server_admin'), ('bot', '0052_auto_20200629_1553'), ('bot', '0053_stocks'), ('bot', '0054_server_secret'), ('bot', '0055_auto_20200723_1042'), ('bot', '0056_auto_20200724_1235'), ('bot', '0057_assist'), ('bot', '0058_delete_assist'), ('bot', '0059_wars'), ('bot', '0060_remove_credential_chat_delete_chat_delete_credential'), ('bot', '0061_server_start'), ('bot', '0062_server_donations'), ('bot', '0063_server_end_server_n_donations'), ('bot', '0064_delete_rackets_remove_server_bot_and_more')]

    initial = True

    dependencies = [
        ('player', '0055_remove_player_botperm'),
        ('faction', '0049_faction_discordname'),
        ('player', '0027_playerdata_ipsban'),
        ('chain', '0078_stat'),
        ('player', '0035_player_attacksupda'),
        ('faction', '0051_faction_livelength'),
        ('player', '0025_player_did'),
    ]

    operations = [
    ]
