# Generated by Django 2.2.7 on 2019-11-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='BOT_TOKEN', max_length=512, unique=True)),
                ('variables', models.TextField(default='{}')),
            ],
        ),
    ]
