# Generated by Django 2.2.7 on 2019-12-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20191202_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='name',
            field=models.CharField(default='BOT_NAME', max_length=32),
        ),
    ]
