# Generated by Django 2.2.7 on 2019-12-03 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0078_stat'),
        ('player', '0027_playerdata_ipsban'),
        ('bot', '0004_configuration_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationHelper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guildId', models.BigIntegerField(default=0)),
                ('stockModule', models.BooleanField(default=False)),
                ('stockWSSB', models.BooleanField(default=False)),
                ('stockTCB', models.BooleanField(default=False)),
                ('lootModule', models.BooleanField(default=False)),
                ('verifyModule', models.BooleanField(default=False)),
                ('verifyForce', models.BooleanField(default=False)),
                ('repoModule', models.BooleanField(default=False)),
                ('repoName', models.CharField(default='repo_token', max_length=64)),
                ('repoToken', models.CharField(default='repo_name', max_length=32)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Configuration')),
                ('verifyFactions', models.ManyToManyField(to='chain.Faction')),
                ('verifyKeys', models.ManyToManyField(to='player.Player')),
            ],
        ),
    ]
