# Generated by Django 2.2.7 on 2019-12-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_configurationhelper'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationhelper',
            name='guildName',
            field=models.CharField(default='guild_name', max_length=32),
        ),
    ]
