# Generated by Django 2.2.7 on 2019-12-03 13:39

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    
    dependencies = [
        ('chain', '0078_stat'),
        ('player', '0027_playerdata_ipsban'),
        ('bot', '0006_configurationhelper_guildname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Configuration',
            new_name='DiscordApp',
        ),
        migrations.RenameModel(
            old_name='ConfigurationHelper',
            new_name='Guild',
        ),
    ]
