# Generated by Django 2.2.7 on 2019-12-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20191203_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='verifyFactions',
            field=models.ManyToManyField(blank=True, to='chain.Faction'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='verifyKeys',
            field=models.ManyToManyField(blank=True, to='player.Player'),
        ),
    ]
