# Generated by Django 2.2.7 on 2019-12-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20191203_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='manageChannels',
            field=models.BooleanField(default=False),
        ),
    ]
