# Generated by Django 2.2.7 on 2019-12-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_guild_stockchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='chainChannel',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='guild',
            name='chainModule',
            field=models.BooleanField(default=False),
        ),
    ]
