# Generated by Django 2.2.7 on 2019-12-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20191212_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guild',
            old_name='verifyKeys',
            new_name='masterKeys',
        ),
        migrations.AddField(
            model_name='guild',
            name='verifyFacsRole',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
