# Generated by Django 2.2.7 on 2019-12-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_auto_20191214_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='guildOwnerId',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guild',
            name='guildOwnerName',
            field=models.CharField(default='guild_owner', max_length=32),
        ),
    ]
