# Generated by Django 3.0.1 on 2020-01-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_auto_20200107_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='verifyAppendFacId',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='guild',
            name='verifyChangeName',
            field=models.BooleanField(default=True),
        ),
    ]
