# Generated by Django 3.0.1 on 2020-01-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_auto_20200116_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='reviveModule',
            field=models.BooleanField(default=False),
        ),
    ]
