# Generated by Django 3.0.1 on 2020-02-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_guild_revivemodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tId', models.IntegerField(default=0)),
                ('secret', models.CharField(default='secret', max_length=128)),
                ('update', models.IntegerField(default=0)),
                ('check', models.CharField(default='secret', max_length=128)),
            ],
        ),
    ]
