# Generated by Django 3.0.1 on 2020-02-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='key',
            field=models.CharField(default='key', max_length=128),
        ),
        migrations.AlterField(
            model_name='chat',
            name='check',
            field=models.CharField(default='check', max_length=128),
        ),
    ]
