# Generated by Django 3.0.1 on 2020-02-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_auto_20200204_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='tId',
            new_name='uid',
        ),
        migrations.AddField(
            model_name='chat',
            name='hookurl',
            field=models.CharField(default='url', max_length=512),
        ),
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default='secret', max_length=128),
        ),
    ]
