# Generated by Django 3.0.1 on 2020-02-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_auto_20200204_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guild',
            name='verifyChangeName',
        ),
        migrations.AddField(
            model_name='guild',
            name='verifyDailyCheck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guild',
            name='verifyDailyVerify',
            field=models.BooleanField(default=False),
        ),
    ]
