# Generated by Django 3.0.1 on 2020-02-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_auto_20200206_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='manageChannels',
            field=models.BooleanField(default=True),
        ),
    ]
