# Generated by Django 3.0.1 on 2020-02-09 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_auto_20200206_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='update',
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('secret', models.CharField(default='secret', max_length=128)),
                ('timestamp', models.IntegerField(default=0)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Chat')),
            ],
        ),
    ]
