# Generated by Django 2.0.7 on 2020-02-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_auto_20200209_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='verifyFactions',
            field=models.ManyToManyField(blank=True, to='faction.Faction'),
        ),
    ]
