# Generated by Django 2.0.7 on 2020-02-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0025_auto_20200211_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guild',
            name='verifyFactions',
        ),
    ]
