# Generated by Django 2.0.7 on 2020-02-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faction', '0049_faction_discordname'),
        ('bot', '0026_remove_guild_verifyfactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='verifyFactions',
            field=models.ManyToManyField(blank=True, to='faction.Faction'),
        ),
    ]
