# Generated by Django 3.0.1 on 2020-02-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0028_auto_20200214_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guild',
            name='allowedRoles',
        ),
        migrations.AddField(
            model_name='guild',
            name='apiRoles',
            field=models.CharField(blank=True, default='["*"]', max_length=64),
        ),
    ]
