# Generated by Django 3.0.1 on 2020-02-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0029_auto_20200214_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='systemChannel',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
