# Generated by Django 3.0.1 on 2020-02-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0031_auto_20200220_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='apiModule',
            field=models.BooleanField(default=False),
        ),
    ]
