# Generated by Django 3.0.1 on 2020-02-20 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0035_player_attacksupda'),
        ('faction', '0051_faction_livelength'),
        ('bot', '0033_discordapp_administrators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='apiChannels',
            field=models.CharField(blank=True, default='["*"]', help_text='Name of the channels where API commands are allowed. Keep ["*"] for all channels allowed. It has to be the exact channel name: ["channel-a", "my-other-channel"]', max_length=64),
        ),
        migrations.AlterField(
            model_name='guild',
            name='apiModule',
            field=models.BooleanField(default=False, help_text='Enable the API module'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='apiRoles',
            field=models.CharField(blank=True, default='["*"]', help_text='Name of the role allowed to use the API commands. Keep ["*"] for all roles allowed. It has to be the exact role name: ["RoleA", "MyOtherRole"] (no @)', max_length=64),
        ),
        migrations.AlterField(
            model_name='guild',
            name='botContactId',
            field=models.IntegerField(default=0, help_text='Your torn ID'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='botContactName',
            field=models.CharField(default='', help_text='Your torn name', max_length=32),
        ),
        migrations.AlterField(
            model_name='guild',
            name='chainChannels',
            field=models.CharField(blank=True, default='["chain"]', help_text='Name of the chain channels. Can be multiple channels. It has to be the exact channel name: ["channel-a", "my-other-channel"]', max_length=64),
        ),
        migrations.AlterField(
            model_name='guild',
            name='chainModule',
            field=models.BooleanField(default=False, help_text='Enable the Chain module'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='configuration',
            field=models.ForeignKey(help_text='Select the bot', on_delete=django.db.models.deletion.CASCADE, to='bot.DiscordApp'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='guildContactId',
            field=models.IntegerField(default=0, help_text='The torn ID of the player that want the bot'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='guildContactName',
            field=models.CharField(default='guild_contact', help_text='The torn name of the player that want the bot', max_length=32),
        ),
        migrations.AlterField(
            model_name='guild',
            name='guildId',
            field=models.BigIntegerField(default=0, help_text='Get the server ID from the message sent by the bot when it joined the server'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='guildOwnerId',
            field=models.BigIntegerField(default=0, help_text='Automatically filled by the bot'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='guildOwnerName',
            field=models.CharField(default='guild_owner', help_text='Automatically filled by the bot', max_length=32),
        ),
        migrations.AlterField(
            model_name='guild',
            name='lootChannels',
            field=models.CharField(blank=True, default='["loot"]', help_text='Name of the loot channels. Can be multiple channels. It has to be the exact channel name: ["channel-a", "my-other-channel"]', max_length=64),
        ),
        migrations.AlterField(
            model_name='guild',
            name='lootModule',
            field=models.BooleanField(default=False, help_text='Enable the Loot module'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='manageChannels',
            field=models.BooleanField(default=True, help_text='The bot will create channels and roles. Better keep True at least on setup.'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='masterKeys',
            field=models.ManyToManyField(blank=True, help_text="Enter torn ID or name to find the player. If it doesn't show up it means the player is not on YATA.", to='player.Player'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='reviveChannels',
            field=models.CharField(blank=True, default='["revive"]', help_text='Name of the revive channels. Can be multiple channels. It has to be the exact channel name: ["channel-a", "my-other-channel"]', max_length=64),
        ),
        migrations.AlterField(
            model_name='guild',
            name='reviveModule',
            field=models.BooleanField(default=False, help_text='Enable the Revive module'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='stockAlerts',
            field=models.BooleanField(default=False, help_text='Enable Alerts'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='stockChannels',
            field=models.CharField(blank=True, default='["stocks"]', help_text='Name of the stock alert channels. Can be multiple channels. It has to be the exact channel name: ["channel-a", "my-other-channel"]', max_length=64),
        ),
        migrations.AlterField(
            model_name='guild',
            name='stockModule',
            field=models.BooleanField(default=False, help_text='Enable the Stock module'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='stockTCB',
            field=models.BooleanField(default=False, help_text='Enable TCB'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='stockWSSB',
            field=models.BooleanField(default=False, help_text='Enable WSSB'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='systemChannel',
            field=models.CharField(blank=True, default='', help_text='Dummy', max_length=32),
        ),
        migrations.AlterField(
            model_name='guild',
            name='verifyAppendFacId',
            field=models.BooleanField(default=True, help_text='Append or not the ID in the faction role.'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='verifyChannels',
            field=models.CharField(blank=True, default='["verify-id"]', help_text='Name of the verify channels. Can be multiple channels. It has to be the exact channel name: ["channel-a", "my-other-channel"]', max_length=64),
        ),
        migrations.AlterField(
            model_name='guild',
            name='verifyDailyCheck',
            field=models.BooleanField(default=False, help_text="Do automatic '!checkFactions force' every 12 hours"),
        ),
        migrations.AlterField(
            model_name='guild',
            name='verifyDailyVerify',
            field=models.BooleanField(default=False, help_text="Do automatic '!verifyAll force' every 12 hours"),
        ),
        migrations.AlterField(
            model_name='guild',
            name='verifyFacsRole',
            field=models.CharField(blank=True, default='', help_text='Name of the faction role.', max_length=16),
        ),
        migrations.AlterField(
            model_name='guild',
            name='verifyFactions',
            field=models.ManyToManyField(blank=True, help_text="Enter faction ID or name to find the faction. If it doesn't show up it means that the faction is not on YATA.", to='faction.Faction'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='verifyForce',
            field=models.BooleanField(default=False, help_text='PM players on join or not'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='verifyModule',
            field=models.BooleanField(default=False, help_text='Enable the Verify module'),
        ),
    ]
