# Generated by Django 3.0.1 on 2020-03-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0036_auto_20200223_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='guildJoinedTime',
            field=models.IntegerField(default=0, help_text='Timestamp when the bot joined the guild (automatic)'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='guildOwnerId',
            field=models.BigIntegerField(default=0, help_text='Automatically filled by the bot (automatic)'),
        ),
        migrations.AlterField(
            model_name='guild',
            name='guildOwnerName',
            field=models.CharField(default='guild_owner', help_text='Automatically filled by the bot (automatic)', max_length=32),
        ),
    ]
