# Generated by Django 2.0.7 on 2020-03-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0037_auto_20200302_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='crimesChannels',
            field=models.CharField(blank=True, default='["*"]', help_text='Name of the channels where OC commands are allowed. Keep ["*"] for all channels allowed. It has to be the exact channel name: ["channel-a", "my-other-channel"]', max_length=64),
        ),
        migrations.AddField(
            model_name='guild',
            name='crimesModule',
            field=models.BooleanField(default=False, help_text='Enable Crimes module'),
        ),
    ]
