# Generated by Django 3.0.1 on 2020-03-10 14:32

import bot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0039_auto_20200305_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='apiChannels',
            field=models.CharField(blank=True, default='["*"]', help_text='Name of the channels where API commands are allowed. Keep ["*"] for all channels allowed. It has to be the exact channel name: ["channel-a", "my-other-channel"]', max_length=64, validators=[bot.models.channel_names_reg]),
        ),
        migrations.AlterField(
            model_name='guild',
            name='chainChannels',
            field=models.CharField(blank=True, default='["chain"]', help_text='Name of the chain channels. Can be multiple channels. It has to be the exact channel name: ["channel-a", "my-other-channel"]', max_length=64, validators=[bot.models.channel_names_reg]),
        ),
        migrations.AlterField(
            model_name='guild',
            name='crimesChannels',
            field=models.CharField(blank=True, default='["oc"]', help_text='Name of the channels where OC commands are allowed. Keep ["*"] for all channels allowed. It has to be the exact channel name: ["channel-a", "my-other-channel"]', max_length=64, validators=[bot.models.channel_names_reg]),
        ),
        migrations.AlterField(
            model_name='guild',
            name='lootChannels',
            field=models.CharField(blank=True, default='["loot"]', help_text='Name of the loot channels. Can be multiple channels. It has to be the exact channel name: ["channel-a", "my-other-channel"]', max_length=64, validators=[bot.models.channel_names_reg]),
        ),
        migrations.AlterField(
            model_name='guild',
            name='reviveChannels',
            field=models.CharField(blank=True, default='["revive"]', help_text='Name of the revive channels. Can be multiple channels. It has to be the exact channel name: ["channel-a", "my-other-channel"]', max_length=64, validators=[bot.models.channel_names_reg]),
        ),
        migrations.AlterField(
            model_name='guild',
            name='stockChannels',
            field=models.CharField(blank=True, default='["stocks"]', help_text='Name of the stock alert channels. Can be multiple channels. It has to be the exact channel name: ["channel-a", "my-other-channel"]', max_length=64, validators=[bot.models.channel_names_reg]),
        ),
        migrations.AlterField(
            model_name='guild',
            name='verifyChannels',
            field=models.CharField(blank=True, default='["verify-id"]', help_text='Name of the verify channels. Can be multiple channels. It has to be the exact channel name: ["channel-a", "my-other-channel"]', max_length=64, validators=[bot.models.channel_names_reg]),
        ),
    ]
