# Generated by Django 3.0.4 on 2020-03-31 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0040_auto_20200310_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='key',
        ),
    ]
