# Generated by Django 3.0.4 on 2020-04-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0041_remove_chat_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='hookurl',
            field=models.TextField(default='{}'),
        ),
    ]
