# Generated by Django 3.0.4 on 2020-04-07 10:40

import bot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0043_auto_20200405_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='racketChannels',
            field=models.CharField(blank=True, default='["rackets"]', help_text='Name of the racket channels. Can be multiple channels. It has to be the exact channel name: ["channel-a", "my-other-channel"]', max_length=64, validators=[bot.models.channel_names_reg]),
        ),
        migrations.AddField(
            model_name='guild',
            name='racketModule',
            field=models.BooleanField(default=False, help_text='Enable the Racket module'),
        ),
        migrations.AddField(
            model_name='guild',
            name='racketRoles',
            field=models.CharField(blank=True, default='["rackets"]', help_text='Name of the role to mention. Can be multiple channels. It has to be the exact channel name: ["role-a", "my-other-role"]', max_length=64),
        ),
    ]
