# Generated by Django 3.0.4 on 2020-04-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0044_auto_20200407_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rackets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=0)),
                ('rackets', models.TextField(default='{}')),
            ],
        ),
    ]
