# Generated by Django 3.0.4 on 2020-06-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0046_auto_20200407_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='racketRoles',
            field=models.CharField(blank=True, default='[]', help_text='Name of the role to mention. It has to be the exact role name: ["Role a"] or empty array [] for no mentions.', max_length=64),
        ),
    ]
