# Generated by Django 3.0.4 on 2020-06-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0047_auto_20200614_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guild',
            old_name='guildContactId',
            new_name='guildContactTornId',
        ),
        migrations.RenameField(
            model_name='guild',
            old_name='guildContactName',
            new_name='guildContactTornName',
        ),
        migrations.AddField(
            model_name='guild',
            name='guildContactDiscordId',
            field=models.BigIntegerField(default=0, help_text='The discord ID of the player that want the bot'),
        ),
        migrations.AddField(
            model_name='guild',
            name='guildContactDiscordName',
            field=models.CharField(default='guild_contact', help_text='The discord name of the player that want the bot', max_length=32),
        ),
    ]
