# Generated by Django 3.0.4 on 2020-06-29 13:50

import bot.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0048_auto_20200619_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Name', max_length=32)),
                ('token', models.CharField(default='Default Token', max_length=512, unique=True)),
                ('administrators', models.TextField(default='{}')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverId', models.BigIntegerField(default=0, help_text='Discrod server id')),
                ('name', models.CharField(default='Default name', help_text='Discord server name', max_length=64)),
                ('configuration', models.TextField(default='{}', help_text='Server name configuration (json)', validators=[bot.models.check_json])),
                ('bot', models.ForeignKey(help_text='Select the bot', on_delete=django.db.models.deletion.CASCADE, to='bot.Bot')),
            ],
        ),
    ]
