# Generated by Django 3.0.4 on 2020-06-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0055_remove_player_botperm'),
        ('bot', '0050_auto_20200629_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='server_admin',
            field=models.ManyToManyField(blank=True, help_text="Enter torn ID or name to find the player. If it doesn't show up it means the player is not on YATA.", to='player.Player'),
        ),
    ]
