# Generated by Django 3.0.4 on 2020-06-29 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0051_server_server_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='server_id',
            new_name='discord_id',
        ),
    ]
