# Generated by Django 3.0.8 on 2020-07-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0054_server_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guild',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='masterKeys',
        ),
        migrations.RemoveField(
            model_name='guild',
            name='verifyFactions',
        ),
        migrations.DeleteModel(
            name='DiscordApp',
        ),
        migrations.DeleteModel(
            name='Guild',
        ),
    ]
