# Generated by Django 3.0.8 on 2020-07-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0055_auto_20200723_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='administrators',
        ),
        migrations.AddField(
            model_name='bot',
            name='number_of_servers',
            field=models.IntegerField(default=0, help_text='Number of servers'),
        ),
    ]
