# Generated by Django 3.1.5 on 2021-02-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0056_auto_20200724_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.IntegerField(default=0)),
                ('target_name', models.CharField(default='Player', max_length=32)),
                ('player_id', models.IntegerField(default=0)),
                ('player_name', models.CharField(default='Player', max_length=32)),
            ],
        ),
    ]
