# Generated by Django 3.1.5 on 2021-02-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0057_assist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assist',
        ),
    ]
