# Generated by Django 4.0.2 on 2022-02-02 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0059_wars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='chat',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Credential',
        ),
    ]
