# Generated by Django 4.0.5 on 2022-08-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0061_server_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='donations',
            field=models.TextField(default='{}', help_text='Donations (autofill by crontab)'),
        ),
    ]
