# Generated by Django 4.0.5 on 2022-08-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0062_server_donations'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='end',
            field=models.IntegerField(default=0, help_text='Date of the end of the contract (computed by crontabs)'),
        ),
        migrations.AddField(
            model_name='server',
            name='n_donations',
            field=models.IntegerField(default=0, help_text='Number of donations (computed by crontabs)'),
        ),
    ]
