# Generated by Django 4.0.5 on 2024-02-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0063_server_end_server_n_donations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rackets',
        ),
        migrations.RemoveField(
            model_name='server',
            name='bot',
        ),
        migrations.RemoveField(
            model_name='server',
            name='server_admin',
        ),
        migrations.DeleteModel(
            name='Stocks',
        ),
        migrations.DeleteModel(
            name='Wars',
        ),
        migrations.DeleteModel(
            name='Bot',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
    ]
