# Generated by Django 3.1.2 on 2020-11-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20201117_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='rating_required',
            new_name='rrp',
        ),
    ]
