# Generated by Django 3.1.2 on 2020-11-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20201117_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.CharField(default='Default description', max_length=256),
        ),
        migrations.AlterField(
            model_name='special',
            name='effect',
            field=models.CharField(default='Default position name', max_length=256),
        ),
    ]
