# Generated by Django 3.1.2 on 2020-11-17 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20201117_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tId', models.IntegerField(default=0, unique=True)),
                ('rating', models.IntegerField(default=0)),
                ('name', models.CharField(default='Default company name', max_length=32)),
                ('director', models.IntegerField(default=0)),
                ('employees_hired', models.IntegerField(default=0)),
                ('employees_capacity', models.IntegerField(default=0)),
                ('daily_income', models.BigIntegerField(default=0)),
                ('daily_customers', models.IntegerField(default=0)),
                ('weekly_income', models.BigIntegerField(default=0)),
                ('weekly_customers', models.IntegerField(default=0)),
                ('days_old', models.IntegerField(default=0)),
                ('company_bank', models.BigIntegerField(default=0)),
                ('popularity', models.IntegerField(default=0)),
                ('efficiency', models.IntegerField(default=0)),
                ('environment', models.IntegerField(default=0)),
                ('trains_available', models.IntegerField(default=0)),
                ('advertising_budget', models.IntegerField(default=0)),
                ('upgrades_company_size', models.IntegerField(default=0)),
                ('upgrades_staffroom_size', models.CharField(default='Default company staffroom', max_length=32)),
                ('upgrades_storage_size', models.CharField(default='Default company storage', max_length=32)),
                ('upgrades_storage_space', models.IntegerField(default=0)),
                ('timestamp', models.IntegerField(default=0)),
                ('company_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companydescription')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tId', models.IntegerField(default=0)),
                ('name', models.CharField(default='Default employee name', max_length=32)),
                ('position', models.CharField(default='Default employee position', max_length=32)),
                ('days_in_company', models.IntegerField(default=0)),
                ('last_action', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
