# Generated by Django 3.1.2 on 2020-11-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='effectiveness_addiction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='effectiveness_director_education',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='effectiveness_settled_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='effectiveness_working_stats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='endurance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='intelligence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='manual_labor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='wage',
            field=models.IntegerField(default=0),
        ),
    ]
