# Generated by Django 3.1.2 on 2020-11-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20201117_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='effectiveness_inactivity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='effectiveness_management',
            field=models.IntegerField(default=0),
        ),
    ]
