# Generated by Django 3.1.2 on 2020-11-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_companydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='effectiveness_total',
            field=models.IntegerField(default=0),
        ),
    ]
