# Generated by Django 3.1.2 on 2020-11-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_employee_effectiveness_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='effectiveness_neg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='effectiveness_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companydata',
            name='effectiveness_neg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companydata',
            name='effectiveness_total',
            field=models.IntegerField(default=0),
        ),
    ]
