# Generated by Django 3.1.2 on 2020-11-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_company_director_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='effectiveness_book_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
