# Generated by Django 3.1.2 on 2020-11-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_employee_effectiveness_book_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='director_hrm',
            field=models.BooleanField(default=False),
        ),
    ]
