# Generated by Django 3.1.2 on 2020-11-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_company_director_hrm'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='effectiveness_ws_act',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='effectiveness_ws_max',
            field=models.IntegerField(default=0),
        ),
    ]
