# Generated by Django 3.1.2 on 2020-11-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_companydata_total_wage'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='total_wage',
            field=models.IntegerField(default=0),
        ),
    ]
