# Generated by Django 3.1.2 on 2020-11-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_company_total_wage'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='daily_profit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companydata',
            name='weekly_profit',
            field=models.IntegerField(default=0),
        ),
    ]
