# Generated by Django 3.1.2 on 2020-11-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_auto_20201126_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='effectiveness_neg',
        ),
        migrations.RemoveField(
            model_name='companydata',
            name='effectiveness_neg',
        ),
        migrations.AddField(
            model_name='company',
            name='effectiveness_addiction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='effectiveness_book_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='effectiveness_director_education',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='effectiveness_inactivity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='effectiveness_management',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='effectiveness_settled_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='effectiveness_working_stats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companydata',
            name='effectiveness_addiction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companydata',
            name='effectiveness_book_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companydata',
            name='effectiveness_director_education',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companydata',
            name='effectiveness_inactivity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companydata',
            name='effectiveness_management',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companydata',
            name='effectiveness_settled_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companydata',
            name='effectiveness_working_stats',
            field=models.IntegerField(default=0),
        ),
    ]
