# Generated by Django 3.1.2 on 2020-11-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_auto_20201126_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='daily_profit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='weekly_profit',
            field=models.IntegerField(default=0),
        ),
    ]
