# Generated by Django 3.1.2 on 2020-11-29 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_auto_20201126_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='abv',
            field=models.CharField(default='-', max_length=4),
        ),
        migrations.CreateModel(
            name='CompanyStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ts', models.IntegerField(default=0)),
                ('timestamp', models.IntegerField(default=0)),
                ('positions', models.TextField(default='{}')),
                ('name', models.CharField(default='Stock', max_length=32)),
                ('cost', models.IntegerField(default=0)),
                ('rrp', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('in_stock', models.IntegerField(default=0)),
                ('on_order', models.IntegerField(default=0)),
                ('sold_amount', models.IntegerField(default=0)),
                ('sold_worth', models.IntegerField(default=0)),
                ('created', models.IntegerField(default=0)),
                ('delta_in_stock', models.IntegerField(default=0)),
                ('delta_created', models.IntegerField(default=0)),
                ('delta_sold_worth', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
