# Generated by Django 3.1.2 on 2021-01-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_auto_20210104_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystock',
            name='delta_sold_amount',
            field=models.IntegerField(default=0),
        ),
    ]
