# Generated by Django 3.1.5 on 2021-07-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_auto_20210730_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='shareId',
            field=models.SlugField(blank=True, default='', max_length=32, null=True),
        ),
    ]
