# Generated by Django 4.0.2 on 2022-03-30 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_company_shareid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='effectiveness_book_bonus',
            new_name='effectiveness_book',
        ),
        migrations.RenameField(
            model_name='companydata',
            old_name='effectiveness_book_bonus',
            new_name='effectiveness_book',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='effectiveness_book_bonus',
            new_name='effectiveness_book',
        ),
    ]
