# Generated by Django 4.2.25 on 2026-07-03 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0030_companydata_daily_stockcost"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyListing",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tId", models.IntegerField(default=0, unique=True)),
                ("name", models.CharField(default="", max_length=128)),
                ("rating", models.IntegerField(default=0)),
                ("director", models.IntegerField(default=0)),
                ("employees_hired", models.IntegerField(default=0)),
                ("employees_capacity", models.IntegerField(default=0)),
                ("daily_income", models.BigIntegerField(default=0)),
                ("daily_customers", models.IntegerField(default=0)),
                ("weekly_income", models.BigIntegerField(default=0)),
                ("weekly_customers", models.IntegerField(default=0)),
                ("days_old", models.IntegerField(default=0)),
                ("appsclosed", models.BooleanField(default=False)),
                ("updated", models.IntegerField(default=0)),
                ("company_type", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="company.companydescription")),
            ],
        ),
    ]
