# Generated by Django 2.0.5 on 2018-08-19 21:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorisedId', models.CharField(default='', max_length=200)),
                ('nItems', models.IntegerField(default=10)),
                ('lastScan', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tId', models.IntegerField(unique=True)),
                ('tName', models.CharField(max_length=200)),
                ('tType', models.CharField(max_length=200)),
                ('tDescription', models.TextField(default='')),
                ('tMarketValue', models.BigIntegerField(default=0)),
                ('tSellPrice', models.BigIntegerField(default=0)),
                ('tBuyPrice', models.BigIntegerField(default=0)),
                ('tCirculation', models.BigIntegerField(default=0)),
                ('tImage', models.URLField(max_length=500)),
                ('onMarket', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.BigIntegerField(default=0)),
                ('quantity', models.BigIntegerField(default=1)),
                ('cost', models.BigIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Duke', max_length=100)),
                ('playerId', models.BigIntegerField(default=4)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('nLog', models.IntegerField(default=1)),
                ('itemsId', models.TextField(blank=True, default='')),
            ],
        ),
    ]
