# Generated by Django 2.0.5 on 2018-08-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0002_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='apiKey',
            field=models.CharField(default='', max_length=16),
        ),
    ]
