# Generated by Django 2.0.5 on 2018-08-28 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0004_itemupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='player',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
