# Generated by Django 2.1 on 2018-08-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0007_item_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstThree', models.CharField(default='Nothing', max_length=100)),
                ('numberUpdates', models.IntegerField(default=0)),
                ('numberPlayers', models.IntegerField(default=0)),
            ],
        ),
    ]
