# Generated by Django 2.0.5 on 2019-05-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0009_stat_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='lastScan',
        ),
        migrations.AddField(
            model_name='config',
            name='lastScanTS',
            field=models.IntegerField(default=0),
        ),
    ]
