# Generated by Django 2.0.5 on 2019-05-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0010_auto_20190508_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date',
        ),
        migrations.RemoveField(
            model_name='itemupdate',
            name='date',
        ),
        migrations.AddField(
            model_name='item',
            name='lastUpdateTS',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemupdate',
            name='lastUpdateTS',
            field=models.IntegerField(default=0),
        ),
    ]
