# Generated by Django 2.0.7 on 2019-05-09 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0011_auto_20190508_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemupdate',
            name='item',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Stat',
        ),
        migrations.RemoveField(
            model_name='config',
            name='autorisedId',
        ),
        migrations.DeleteModel(
            name='ItemUpdate',
        ),
    ]
