# Generated by Django 2.0.5 on 2019-05-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0013_auto_20190509_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='apiString',
            field=models.CharField(default='0', max_length=330),
        ),
    ]
