# Generated by Django 2.0.5 on 2019-06-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0014_preference_apistring'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tEffect',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='tRequirement',
            field=models.TextField(default=''),
        ),
    ]
