# Generated by Django 2.0.5 on 2019-06-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0015_auto_20190608_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketdata',
            name='sellId',
        ),
        migrations.AddField(
            model_name='marketdata',
            name='itemmarket',
            field=models.BooleanField(default=False),
        ),
    ]
