# Generated by Django 2.0.7 on 2019-06-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0016_auto_20190610_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stockB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='stockD',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='stockI',
            field=models.IntegerField(default=0),
        ),
    ]
