# Generated by Django 2.0.5 on 2019-07-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0017_auto_20190618_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='priceHistory',
            field=models.TextField(default={}),
        ),
    ]
