# Generated by Django 2.0.5 on 2019-07-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0018_item_pricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='priceTendancyA',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='priceTendancyB',
            field=models.FloatField(default=0.0),
        ),
    ]
