# Generated by Django 2.0.5 on 2019-07-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0019_auto_20190723_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='priceTendancy',
            field=models.FloatField(default=0.0),
        ),
    ]
