# Generated by Django 2.0.7 on 2019-07-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0020_item_pricetendancy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='priceTendancy',
            new_name='monthTendancy',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='priceTendancyA',
            new_name='monthTendancyA',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='priceTendancyB',
            new_name='monthTendancyB',
        ),
        migrations.AddField(
            model_name='item',
            name='weekTendancy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='weekTendancyA',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='weekTendancyB',
            field=models.FloatField(default=0.0),
        ),
    ]
