# Generated by Django 2.0.7 on 2019-07-24 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0021_auto_20190724_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='monthTendancy',
            new_name='monthTendency',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='monthTendancyA',
            new_name='monthTendencyA',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='monthTendancyB',
            new_name='monthTendencyB',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='weekTendancy',
            new_name='weekTendency',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='weekTendancyA',
            new_name='weekTendencyA',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='weekTendancyB',
            new_name='weekTendencyB',
        ),
    ]
