# Generated by Django 2.0.5 on 2019-09-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0022_auto_20190724_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='territoryTS',
            field=models.IntegerField(default=0),
        ),
    ]
