# Generated by Django 3.0.4 on 2020-05-22 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0024_auto_20191029_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbroadStocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=32)),
                ('quantity', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('timestamp', models.IntegerField(default=0)),
                ('uid', models.IntegerField(default=0)),
                ('client', models.CharField(blank=True, max_length=32)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazaar.Item')),
            ],
        ),
    ]
