# Generated by Django 3.0.4 on 2020-05-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0025_abroadstocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='abroadstocks',
            name='last',
            field=models.BooleanField(default=True),
        ),
    ]
