# Generated by Django 3.0.4 on 2020-05-24 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0027_auto_20200523_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abroadstocks',
            name='uid',
        ),
    ]
