# Generated by Django 3.0.4 on 2020-05-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0030_auto_20200525_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abroadstocks',
            name='client',
            field=models.CharField(blank=True, default='unknown [0.0]', max_length=32),
        ),
        migrations.AlterField(
            model_name='verifiedclient',
            name='version',
            field=models.CharField(default='0.0', max_length=16),
        ),
    ]
