# Generated by Django 3.0.4 on 2020-05-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0032_auto_20200526_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abroadstocks',
            name='client',
            field=models.CharField(blank=True, default='unknown [0.0]', max_length=64),
        ),
        migrations.AlterField(
            model_name='verifiedclient',
            name='name',
            field=models.CharField(default='?', max_length=64),
        ),
    ]
