# Generated by Django 3.0.8 on 2020-09-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0033_auto_20200526_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazaardata',
            name='pointsValue',
            field=models.IntegerField(default=0),
        ),
    ]
