# Generated by Django 3.1.1 on 2020-10-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0034_bazaardata_pointsvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazaardata',
            name='clientsStats',
            field=models.TextField(default='{}'),
        ),
    ]
