# Generated by Django 3.1.7 on 2021-04-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0035_bazaardata_clientsstats'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='abroadstocks',
            index=models.Index(fields=['country_key'], name='bazaar_abro_country_086462_idx'),
        ),
        migrations.AddIndex(
            model_name='abroadstocks',
            index=models.Index(fields=['item_id', 'country_key'], name='bazaar_abro_item_id_0e8aca_idx'),
        ),
        migrations.AddIndex(
            model_name='abroadstocks',
            index=models.Index(fields=['timestamp'], name='bazaar_abro_timesta_b47b39_idx'),
        ),
    ]
