# Generated by Django 3.1.5 on 2021-03-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0035_bazaardata_clientsstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazaardata',
            name='typeItem',
            field=models.TextField(default='{}'),
        ),
    ]
