# Generated by Django 4.2.18 on 2025-09-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bazaar", "0036_bazaardata_typeitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="lastSeenAbroad",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="seenAbroad",
            field=models.BooleanField(default=False),
        ),
    ]
