# Generated by Django 2.0.2 on 2018-02-11 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=8)),
                ('stockKeys', models.CharField(default='', max_length=200)),
                ('nItems', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tId', models.IntegerField(unique=True)),
                ('tName', models.CharField(max_length=200)),
                ('tType', models.CharField(max_length=200)),
                ('tMarketValue', models.BigIntegerField(default=0)),
                ('tImage', models.URLField(max_length=500)),
                ('onMarket', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0)),
                ('quantity', models.BigIntegerField(default=1)),
                ('cost', models.BigIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sets.Item')),
            ],
        ),
        migrations.CreateModel(
            name='userStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='0', max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sets.Item')),
            ],
        ),
    ]
