# Generated by Django 2.0.2 on 2018-02-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0002_item_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tDescription',
            field=models.TextField(default=''),
        ),
    ]
