# Generated by Django 2.0.5 on 2018-06-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0003_item_tdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='key',
            field=models.SlugField(max_length=16),
        ),
    ]
