# Generated by Django 2.0.5 on 2018-07-10 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0004_auto_20180606_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Duke', max_length=100)),
                ('user_id', models.BigIntegerField(default=4)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
