# Generated by Django 2.0.7 on 2018-07-16 11:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0005_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='login',
            name='n_log',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='logindate',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sets.login'),
        ),
    ]
