# Generated by Django 2.0.5 on 2018-07-31 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0006_auto_20180716_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstock',
            name='item',
        ),
        migrations.DeleteModel(
            name='userStock',
        ),
    ]
