# Generated by Django 2.0.5 on 2018-07-31 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0007_auto_20180731_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='stockKeys',
            new_name='autorisedId',
        ),
        migrations.RemoveField(
            model_name='config',
            name='key',
        ),
    ]
