# Generated by Django 2.0.5 on 2018-07-31 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0008_auto_20180731_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='lastScan',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
