# Generated by Django 2.0.5 on 2018-07-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0009_config_lastscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tCirculation',
            field=models.BigIntegerField(default=0),
        ),
    ]
