# Generated by Django 2.0.5 on 2018-07-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0010_item_tcirculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tBuyPrice',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='tSellPrice',
            field=models.BigIntegerField(default=0),
        ),
    ]
