# Generated by Django 2.0.5 on 2018-08-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0011_auto_20180731_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='items',
            field=models.TextField(default=''),
        ),
    ]
