# Generated by Django 2.0.5 on 2018-08-17 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0012_login_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='items',
            new_name='items_id',
        ),
    ]
