# Generated by Django 3.1.5 on 2021-04-14 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20210414_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='current_price_previous',
            new_name='previous_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='tendancy_l_b',
        ),
    ]
