# Generated by Django 3.1.5 on 2021-04-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20210414_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='market_cap',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='history',
            name='total_shares',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='market_cap',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='total_shares',
            field=models.BigIntegerField(default=0),
        ),
    ]
