# Generated by Django 3.1.5 on 2021-04-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20210415_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='torn_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
