# Generated by Django 2.0.5 on 2019-07-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=0)),
                ('key', models.CharField(max_length=20)),
                ('a', models.TextField(default='{}')),
            ],
        ),
    ]
