# Generated by Django 2.0.5 on 2019-10-25 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_donation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Call',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
