# Generated by Django 2.0.5 on 2019-10-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('awards', '0003_auto_20191025_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=0)),
                ('apicall', models.TextField(default='{}')),
                ('hofHistogram', models.TextField(default='{}')),
            ],
        ),
    ]
